#!/bin/sh
_thispath=$(dirname $0)
_pwd=$(pwd)

trap "sed -i '$ d' ${_pwd}/conf/local.conf" EXIT

echo "SCA_AVAILABLE_MODULES = \"$@\"" >> ${_pwd}/conf/local.conf

bitbake $(${_thispath}/get_buildmodules $@) || exit 1
${_thispath}/check_results ${_pwd}/tmp/deploy/images/*/sca $@ || exit 1
