#!/usr/bin/env python3
import argparse
import yaml
import json
import sys


def create_parser():
    parser = argparse.ArgumentParser(
        prog=__file__, description='Create ansible playboo from json configs')
    parser.add_argument("files", nargs='+', help="Files to parse")
    return parser.parse_args()


if __name__ == '__main__':
    res = [{"hosts": "localhost", "gather_facts": "yes", "roles": []}]
    args = create_parser()

    for f in args.files:
        try:
            with open(f) as i:
                res[0]["roles"].append(json.load(i))
        except Exception as e:
            sys.stderr.write("Can't use {}: {}\n".format(f, e))
    try:
        print(yaml.dump(res))
    except Exception as e:
        sys.stderr.write("{}\n".format(e))
