SRC_URI_append = " https://proxy.golang.org/github.com/opentracing-contrib/go-observer/@v/v0.0.0-20170622124052-a52f23424492.zip;srcoutput=github.com/opentracing-contrib/go-observer;srcinput=github.com/opentracing-contrib/go-observer@v0.0.0-20170622124052-a52f23424492;downloadfilename=github-com-opentracing-contrib-go-observer-0.0.0-20170622124052-a52f23424492.zip;name=github-com-opentracing-contrib-go-observer"
SRC_URI[github-com-opentracing-contrib-go-observer.sha256sum] = "50023eee1ef04412410f43d8b5dcf3ef481c0fc39067add27799654705fa84b2"

MOD_LICENSE_append = " \
    Apache-2.0 \
"
LIC_FILES_CHKSUM_append = " \
    file://src/github.com/opentracing-contrib/go-observer/LICENSE;md5=3e430fab283e174e0a070638207cf45f \
"
