SRC_URI_append = " https://proxy.golang.org/github.com/alexkohler/unimport/@v/v0.0.0-20171106223308-e6f2b2e2d406.zip;srcoutput=github.com/alexkohler/unimport;srcinput=github.com/alexkohler/unimport@v0.0.0-20171106223308-e6f2b2e2d406;downloadfilename=github-com-alexkohler-unimport-0.0.0-20171106223308-e6f2b2e2d406.zip;name=github-com-alexkohler-unimport"
SRC_URI[github-com-alexkohler-unimport.sha256sum] = "06975e39670577ae96653bd5a6b29f8882be447c7e2d46c12444302067e7ca7f"

MOD_LICENSE_append = " \
    MIT \
"
LIC_FILES_CHKSUM_append = " \
    file://src/github.com/alexkohler/unimport/LICENSE;md5=2c7b8f9e174db37605a15c992b0dc995 \
"
