SRC_URI_append = " https://proxy.golang.org/github.com/jcmturner/dnsutils/v2/@v/v2.0.0.zip;srcoutput=github.com/jcmturner/dnsutils/v2;srcinput=github.com/jcmturner/dnsutils/v2@v2.0.0;downloadfilename=github-com-jcmturner-dnsutils-v2-2.0.0.zip;name=github-com-jcmturner-dnsutils-v2"
SRC_URI[github-com-jcmturner-dnsutils-v2.sha256sum] = "f9188186b672e547cfaef66107aa62d65054c5d4f10d4dcd1ff157d6bf8c275d"

MOD_LICENSE_append = " \
    Apache-2.0 \
"
LIC_FILES_CHKSUM_append = " \
    file://src/github.com/jcmturner/dnsutils/v2/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327 \
"
