SRC_URI_append = " https://proxy.golang.org/github.com/mwitkow/go-proto-validators/@v/v0.3.2.zip;srcoutput=github.com/mwitkow/go-proto-validators;srcinput=github.com/mwitkow/go-proto-validators@v0.3.2;downloadfilename=github-com-mwitkow-go-proto-validators-0.3.2.zip;name=github-com-mwitkow-go-proto-validators"
SRC_URI[github-com-mwitkow-go-proto-validators.sha256sum] = "68eb5beb818a44435ece07e88dada8c9bab8f5a4b70a3ca2dce5d5a3eb3421b0"

MOD_LICENSE_append = " \
    Apache-2.0 \
"
LIC_FILES_CHKSUM_append = " \
    file://src/github.com/mwitkow/go-proto-validators/LICENSE.txt;md5=7ab5c73bb7e4679b16dd7c11b3559acf \
"
