SRC_URI_append = " https://proxy.golang.org/github.com/gertd/go-pluralize/@v/v0.1.7.zip;srcoutput=github.com/gertd/go-pluralize;srcinput=github.com/gertd/go-pluralize@v0.1.7;downloadfilename=github-com-gertd-go-pluralize-0.1.7.zip;name=github-com-gertd-go-pluralize"
SRC_URI[github-com-gertd-go-pluralize.sha256sum] = "68777f28d67a2eab7f05b2d1f4b23e8b36d8bd8daa3581289044421544db07ff"

MOD_LICENSE_append = " \
    MIT \
"
LIC_FILES_CHKSUM_append = " \
    file://src/github.com/gertd/go-pluralize/LICENSE;md5=7e0362bb72180462b3e08e0cca202fc9 \
"
