SRC_URI_append = " https://proxy.golang.org/github.com/lightstep/lightstep-tracer-common/golang/gogo/@v/v0.0.0-20210210170715-a8dfcb80d3a7.zip;srcoutput=github.com/lightstep/lightstep-tracer-common/golang/gogo;srcinput=github.com/lightstep/lightstep-tracer-common/golang/gogo@v0.0.0-20210210170715-a8dfcb80d3a7;downloadfilename=github-com-lightstep-lightstep-tracer-common-golang-gogo-0.0.0-20210210170715-a8dfcb80d3a7.zip;name=github-com-lightstep-lightstep-tracer-common-golang-gogo"
SRC_URI[github-com-lightstep-lightstep-tracer-common-golang-gogo.sha256sum] = "b4cdc3a48d9a9f46c14875fb399d6345c17c57940ff58243a0ccd7d670934f5f"

MOD_LICENSE_append = " \
    MIT \
"
LIC_FILES_CHKSUM_append = " \
    file://src/github.com/lightstep/lightstep-tracer-common/golang/gogo/LICENSE;md5=ce5e14e16e13722613cbe38415c54085 \
"
