SRC_URI_append = " https://proxy.golang.org/github.com/viki-org/dnscache/@v/v0.0.0-20130720023526-c70c1f23c5d8.zip;srcoutput=github.com/viki-org/dnscache;srcinput=github.com/viki-org/dnscache@v0.0.0-20130720023526-c70c1f23c5d8;downloadfilename=github-com-viki-org-dnscache-0.0.0-20130720023526-c70c1f23c5d8.zip;name=github-com-viki-org-dnscache"
SRC_URI[github-com-viki-org-dnscache.sha256sum] = "84a5863c345b30a391a2bb8269a326962137fd25f95abab868bae1addf8f9be3"

MOD_LICENSE_append = " \
    MIT \
"
LIC_FILES_CHKSUM_append = " \
    file://src/github.com/viki-org/dnscache/license.txt;md5=4114cb0a88fd194cb14fcef76d3ccec2 \
"
