SRC_URI_append = " https://proxy.golang.org/github.com/ianlancetaylor/demangle/@v/v0.0.0-20210312005511-7a0008c442e6.zip;srcoutput=github.com/ianlancetaylor/demangle;srcinput=github.com/ianlancetaylor/demangle@v0.0.0-20210312005511-7a0008c442e6;downloadfilename=github-com-ianlancetaylor-demangle-0.0.0-20210312005511-7a0008c442e6.zip;name=github-com-ianlancetaylor-demangle"
SRC_URI[github-com-ianlancetaylor-demangle.sha256sum] = "cdbbe9cb2f0ae6d717af2e894f612bdff03113de2d55423111cf5c68b05faf87"

MOD_LICENSE_append = " \
    BSD-3-Clause \
"
LIC_FILES_CHKSUM_append = " \
    file://src/github.com/ianlancetaylor/demangle/LICENSE;md5=81729dc66d48cba483290ca39318923d \
"
