SRC_URI_append = " https://proxy.golang.org/github.com/jgautheron/goconst/@v/v1.4.0.zip;srcoutput=github.com/jgautheron/goconst;srcinput=github.com/jgautheron/goconst@v1.4.0;downloadfilename=github-com-jgautheron-goconst-1.4.0.zip;name=github-com-jgautheron-goconst"
SRC_URI[github-com-jgautheron-goconst.sha256sum] = "23f7d992ad05be70a2e6fd965bd092512bfa356ff01379596e13f5e8ddfca83a"

MOD_LICENSE_append = " \
    MIT \
"
LIC_FILES_CHKSUM_append = " \
    file://src/github.com/jgautheron/goconst/LICENSE;md5=33b2be59a3a3c31e4b98ba1acce08fcb \
"
