SRC_URI_append = " https://proxy.golang.org/github.com/lightstep/lightstep-tracer-go/@v/v0.24.0.zip;srcoutput=github.com/lightstep/lightstep-tracer-go;srcinput=github.com/lightstep/lightstep-tracer-go@v0.24.0;downloadfilename=github-com-lightstep-lightstep-tracer-go-0.24.0.zip;name=github-com-lightstep-lightstep-tracer-go"
SRC_URI[github-com-lightstep-lightstep-tracer-go.sha256sum] = "f0348e7d63a711c5c283e870dec64cca24700394895bab9274aad49329b73ce9"

MOD_LICENSE_append = " \
    MIT \
"
LIC_FILES_CHKSUM_append = " \
    file://src/github.com/lightstep/lightstep-tracer-go/LICENSE;md5=f8c63238785e7e0ca110b323ac0e4481 \
"
