SRC_URI_append = " https://proxy.golang.org/github.com/pkg/diff/@v/v0.0.0-20210226163009-20ebb0f2a09e.zip;srcoutput=github.com/pkg/diff;srcinput=github.com/pkg/diff@v0.0.0-20210226163009-20ebb0f2a09e;downloadfilename=github-com-pkg-diff-0.0.0-20210226163009-20ebb0f2a09e.zip;name=github-com-pkg-diff"
SRC_URI[github-com-pkg-diff.sha256sum] = "f35b23fdd2b9522ddd46cc5c0161b4f0765c514475d5d4ca2a86aca31388c8bd"

MOD_LICENSE_append = " \
    BSD-3-Clause \
"
LIC_FILES_CHKSUM_append = " \
    file://src/github.com/pkg/diff/LICENSE;md5=d0250703509998b3201f5dd7f26e8c35 \
"
