SRC_URI_append = " https://proxy.golang.org/github.com/cpuguy83/go-md2man/v2/@v/v2.0.0.zip;srcoutput=github.com/cpuguy83/go-md2man/v2;srcinput=github.com/cpuguy83/go-md2man/v2@v2.0.0;downloadfilename=github-com-cpuguy83-go-md2man-v2-2.0.0.zip;name=github-com-cpuguy83-go-md2man-v2"
SRC_URI[github-com-cpuguy83-go-md2man-v2.sha256sum] = "f2fdd06287a80f1bea5552f572d7f2314ec829285a3040b63469e0635f66fb6d"

MOD_LICENSE_append = " \
    MIT \
"
LIC_FILES_CHKSUM_append = " \
    file://src/github.com/cpuguy83/go-md2man/v2/LICENSE.md;md5=80794f9009df723bbc6fe19234c9f517 \
"
