SRC_URI_append = " https://proxy.golang.org/github.com/nbutton23/zxcvbn-go/@v/v0.0.0-20210217022336-fa2cb2858354.zip;srcoutput=github.com/nbutton23/zxcvbn-go;srcinput=github.com/nbutton23/zxcvbn-go@v0.0.0-20210217022336-fa2cb2858354;downloadfilename=github-com-nbutton23-zxcvbn-go-0.0.0-20210217022336-fa2cb2858354.zip;name=github-com-nbutton23-zxcvbn-go"
SRC_URI[github-com-nbutton23-zxcvbn-go.sha256sum] = "ceffa831914e8b648effbc6c937c00c1c0287f99b1f0bc039218100c20242f2d"

MOD_LICENSE_append = " \
    MIT \
"
LIC_FILES_CHKSUM_append = " \
    file://src/github.com/nbutton23/zxcvbn-go/LICENSE.txt;md5=558605e5a5fcd98c3b50715b84e80882 \
"
