SRC_URI_append = " https://proxy.golang.org/github.com/ianlancetaylor/demangle/@v/v0.0.0-20210331232236-9bc5433e3b46.zip;srcoutput=github.com/ianlancetaylor/demangle;srcinput=github.com/ianlancetaylor/demangle@v0.0.0-20210331232236-9bc5433e3b46;downloadfilename=github-com-ianlancetaylor-demangle-0.0.0-20210331232236-9bc5433e3b46.zip;name=github-com-ianlancetaylor-demangle"
SRC_URI[github-com-ianlancetaylor-demangle.sha256sum] = "44532bac9580a85c43c98a1317d280f7f3012e941d99990f39e7acb1f2e5aa71"

MOD_LICENSE_append = " \
    BSD-3-Clause \
"
LIC_FILES_CHKSUM_append = " \
    file://src/github.com/ianlancetaylor/demangle/LICENSE;md5=81729dc66d48cba483290ca39318923d \
"
