SRC_URI_append = " https://proxy.golang.org/github.com/jcmturner/aescts/v2/@v/v2.0.0.zip;srcoutput=github.com/jcmturner/aescts/v2;srcinput=github.com/jcmturner/aescts/v2@v2.0.0;downloadfilename=github-com-jcmturner-aescts-v2-2.0.0.zip;name=github-com-jcmturner-aescts-v2"
SRC_URI[github-com-jcmturner-aescts-v2.sha256sum] = "717a211ad4aac248cf33cadde73059c13f8e9462123a0ab2fed5c5e61f7739d7"

MOD_LICENSE_append = " \
    Apache-2.0 \
"
LIC_FILES_CHKSUM_append = " \
    file://src/github.com/jcmturner/aescts/v2/LICENSE;md5=e3fc50a88d0a364313df4b21ef20c29e \
"
