SUMMARY = "contextlib2 is a backport of the standard library's contextlib module to earlier Python versions"
DESCRIPTION = "contextlib2 is a backport of the standard library's contextlib module to earlier Python versions"
HOMEPAGE = "https://github.com/jazzband/contextlib2"
LICENSE = "Python-2.0"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=43d1c7827e8fad6454b553caf0e1d734"

PYPI_PACKAGE = "contextlib2"

inherit pypi
inherit native
