## SPDX-License-Identifier: BSD-2-Clause
## Copyright (c) 2019, Konrad Weihmann

SCA_YARA_EXTRA_SUPPRESS ?= ""
SCA_YARA_EXTRA_FATAL ?= ""
SCA_YARA_MODULES ?= "\
                    yara-rules/1aN0rmus/PCAPs.yara \
                    yara-rules/1aN0rmus/exe_rules.yara \
                    yara-rules/1aN0rmus/memory.yara \
                    yara-rules/1aN0rmus/pos_malware.yara \
                    yara-rules/1aN0rmus/rtf_rules.yara \
                    yara-rules/1aN0rmus/web_log_review.yara \
                    yara-rules/1aN0rmus/web_rules.yara \
                    yara-rules/73mp74710n/njrat.yar \
                    yara-rules/AirBnB/MachO.yar \
                    yara-rules/AirBnB/eicar.yar \
                    yara-rules/AirBnB/hacktool_multi_bloodhound_owned.yara \
                    yara-rules/AirBnB/hacktool_multi_jtesta_ssh_mitm.yara \
                    yara-rules/AirBnB/hacktool_multi_masscan.yara \
                    yara-rules/AirBnB/hacktool_multi_ncc_ABPTTS.yara \
                    yara-rules/AirBnB/hacktool_multi_ntlmrelayx.yara \
                    yara-rules/AirBnB/hacktool_multi_pyrasite_py.yara \
                    yara-rules/AirBnB/hacktool_multi_responder_py.yara \
                    yara-rules/AirBnB/malware_multi_pupy_rat.yara \
                    yara-rules/AirBnB/malware_multi_vesche_basicrat.yara \
                    yara-rules/Airbus/derusbi_kernel.yar \
                    yara-rules/Airbus/derusbi_linux.yar \
                    yara-rules/Airbus/sakula_dropper_v3-1.yar \
                    yara-rules/Airbus/sakula_packed_v2-0.yar \
                    yara-rules/Airbus/sakula_packed_v2-1.yar \
                    yara-rules/Airbus/sakula_packed_v2-2.yar \
                    yara-rules/Airbus/sakula_packed_v3-1.yar \
                    yara-rules/Airbus/sakula_v1-0.yar \
                    yara-rules/Airbus/sakula_v1-1.yar \
                    yara-rules/Airbus/sakula_v1-2.yar \
                    yara-rules/Airbus/sakula_v1-3.yar \
                    yara-rules/Airbus/sakula_v1-4.yar \
                    yara-rules/Airbus/sakula_v2-0.yar \
                    yara-rules/Airbus/sakula_v2-1.yar \
                    yara-rules/Airbus/sakula_v2-2.yar \
                    yara-rules/Airbus/sakula_v3-0.yar \
                    yara-rules/Airbus/sakula_v3-1.yar \
                    yara-rules/Airbus/sakula_v3-2.yar \
                    yara-rules/Airbus/sakula_vx_protector.yar \
                    yara-rules/Anomali_Labs/PyInstaller_Binary.yar \
                    yara-rules/ApoNie/HeapLib.yar \
                    yara-rules/Artemonsecurity/snake.yar \
                    yara-rules/Artemonsecurity/snake_packed.yar \
                    yara-rules/BAESystems/Hermes.yar \
                    yara-rules/Booz_Allen_Hamilton/Double_Pulsar_Petya.yar \
                    yara-rules/Booz_Allen_Hamilton/PolishBankRAT.yar \
                    yara-rules/Brian_Carter_-carterb/archives_w_chinapic.yar \
                    yara-rules/Brian_Carter_-carterb/demuzacert.yar \
                    yara-rules/Brian_Carter_-carterb/injector_panel_sqlite.yar \
                    yara-rules/Brian_Carter_-carterb/jar_drops_9002.yar \
                    yara-rules/Brian_Carter_-carterb/mal_pdf.yar \
                    yara-rules/Brian_Carter_-carterb/panelzips.yar \
                    yara-rules/Brian_Carter_-carterb/pony_config.yar \
                    yara-rules/Brian_Carter_-carterb/tables_inject_panel.yar \
                    yara-rules/Brian_Carter_-carterb/vt_pony_post2gate.yar \
                    yara-rules/CSE/APT28_Hospitality.yar \
                    yara-rules/CSE/config_decoder_sigs.yar \
                    yara-rules/Citizen_Lab/3102.yara \
                    yara-rules/Citizen_Lab/9002.yara \
                    yara-rules/Citizen_Lab/bangat.yara \
                    yara-rules/Citizen_Lab/between-hk-and-burma.yara \
                    yara-rules/Citizen_Lab/boouset.yara \
                    yara-rules/Citizen_Lab/comfoo.yara \
                    yara-rules/Citizen_Lab/cookies.yara \
                    yara-rules/Citizen_Lab/cves.yara \
                    yara-rules/Citizen_Lab/cxpid.yara \
                    yara-rules/Citizen_Lab/enfal.yara \
                    yara-rules/Citizen_Lab/ezcob.yara \
                    yara-rules/Citizen_Lab/fakem.yara \
                    yara-rules/Citizen_Lab/favorite.yara \
                    yara-rules/Citizen_Lab/filetypes.yara \
                    yara-rules/Citizen_Lab/glasses.yara \
                    yara-rules/Citizen_Lab/iexpl0re.yara \
                    yara-rules/Citizen_Lab/imuler.yara \
                    yara-rules/Citizen_Lab/insta11.yara \
                    yara-rules/Citizen_Lab/luckycat.yara \
                    yara-rules/Citizen_Lab/lurk0+cctv0.yara \
                    yara-rules/Citizen_Lab/maccontrol.yara \
                    yara-rules/Citizen_Lab/malware-families.yara \
                    yara-rules/Citizen_Lab/mirage.yara \
                    yara-rules/Citizen_Lab/mongal.yara \
                    yara-rules/Citizen_Lab/msattacker.yara \
                    yara-rules/Citizen_Lab/naikon.yara \
                    yara-rules/Citizen_Lab/naspyupdate.yara \
                    yara-rules/Citizen_Lab/nettraveler.yara \
                    yara-rules/Citizen_Lab/nsfree.yara \
                    yara-rules/Citizen_Lab/oleidentifiers.yara \
                    yara-rules/Citizen_Lab/olyx.yara \
                    yara-rules/Citizen_Lab/payloads.yara \
                    yara-rules/Citizen_Lab/plugx.yara \
                    yara-rules/Citizen_Lab/pubsab.yara \
                    yara-rules/Citizen_Lab/quarian.yara \
                    yara-rules/Citizen_Lab/regsubdat.yara \
                    yara-rules/Citizen_Lab/remote.yara \
                    yara-rules/Citizen_Lab/rookie.yara \
                    yara-rules/Citizen_Lab/rooter.yara \
                    yara-rules/Citizen_Lab/safenet.yara \
                    yara-rules/Citizen_Lab/scarhikn.yara \
                    yara-rules/Citizen_Lab/surtr.yara \
                    yara-rules/Citizen_Lab/t5000.yara \
                    yara-rules/Citizen_Lab/vidgrab.yara \
                    yara-rules/Citizen_Lab/warp.yara \
                    yara-rules/Citizen_Lab/wimmie.yara \
                    yara-rules/Citizen_Lab/xtreme.yara \
                    yara-rules/Citizen_Lab/yayih.yara \
                    yara-rules/CyberDefenses/installmonstr.yar \
                    yara-rules/CyberDefenses/u34.yar \
                    yara-rules/CyberDefenses/wirenet_dropper.yar \
                    yara-rules/Damian_Baran/rule_LinuxDDOS_Agent.yar \
                    yara-rules/Didier_Stevens/JPEG_EXIF_Contains_eval.yara \
                    yara-rules/Didier_Stevens/Nviso.yar \
                    yara-rules/Didier_Stevens/PE_PyInstaller.yar \
                    yara-rules/Didier_Stevens/contains_pe_file.yara \
                    yara-rules/Didier_Stevens/contains_vbe_file.yara \
                    yara-rules/Didier_Stevens/maldoc.yara \
                    yara-rules/Didier_Stevens/peid-userdb-rules-with-pe-module.yara \
                    yara-rules/Didier_Stevens/peid-userdb-rules-without-pe-module.yara \
                    yara-rules/Dragonthreatlabs/apt_c16_win32_dropper.yar \
                    yara-rules/Dragonthreatlabs/apt_c16_win64_dropper.yar \
                    yara-rules/Dragonthreatlabs/apt_c16_win_disk_pcclient.yar \
                    yara-rules/Dragonthreatlabs/apt_c16_win_memory_pcclient.yar \
                    yara-rules/Dragonthreatlabs/apt_c16_win_swisyn.yar \
                    yara-rules/Dragonthreatlabs/apt_c16_win_wateringhole.yar \
                    yara-rules/EmersonElectricCo/misc_compressed_exe.yara \
                    yara-rules/EmersonElectricCo/misc_hexascii_pe_in_html.yara \
                    yara-rules/EmersonElectricCo/misc_no_dosmode_header.yara \
                    yara-rules/EmersonElectricCo/misc_ooxml_core_properties.yara \
                    yara-rules/EmersonElectricCo/misc_upx_packed_binary.yara \
                    yara-rules/Fireeye/APT32_ActiveMime_Lure.yar \
                    yara-rules/Fireeye/APT_DeputyDog_Strings.yar \
                    yara-rules/Fireeye/BadRabbit.yar \
                    yara-rules/Fireeye/FE_APT_9002_rat.yar \
                    yara-rules/Fireeye/FE_petya_ransomware,yar \
                    yara-rules/Fireeye/MACROCHECK.YAR \
                    yara-rules/Fireeye/Molerats_certs.yar \
                    yara-rules/Fireeye/TRITON_Framework.yar \
                    yara-rules/Fireeye/callTogether_certificate.yar \
                    yara-rules/Fireeye/qti_certificate.yar \
                    yara-rules/HorribleCanoe/compiled_autoit.yara \
                    yara-rules/HorribleCanoe/connection_manager_phonebook.yara \
                    yara-rules/HorribleCanoe/delphi-wlan.yara \
                    yara-rules/HorribleCanoe/ejects_cdrom.yara \
                    yara-rules/HorribleCanoe/lowers_security.yara \
                    yara-rules/HorribleCanoe/pcre.yara \
                    yara-rules/HorribleCanoe/reads_clipboard.yara \
                    yara-rules/InQuest/AgentTesla.yar \
                    yara-rules/InQuest/CVE_2018_4878_0day_ITW.yar \
                    yara-rules/InQuest/Embedded_PE_File.yar \
                    yara-rules/InQuest/Excel_IQY_File.yar \
                    yara-rules/InQuest/Excel_IQY_File_Suspicious_Request.yar \
                    yara-rules/InQuest/Excel_IQY_File_With_file_extension.yar \
                    yara-rules/InQuest/Hiddenbee.yar \
                    yara-rules/InQuest/MC_Office_DDE.yar \
                    yara-rules/InQuest/Microsoft_Office_Document_with_Embedded_Flash_File.yar \
                    yara-rules/InQuest/NTLM_Credential_Theft_via_PDF.yar \
                    yara-rules/InQuest/RTF_Byte_Nibble_Obfuscation_method.yar \
                    yara-rules/Jipe_/AutoIT.yar \
                    yara-rules/Jipe_/BlackShades.yar \
                    yara-rules/Jipe_/Bolonyokte.yar \
                    yara-rules/Jipe_/Cerberus.yar \
                    yara-rules/Jipe_/Citadel.yar \
                    yara-rules/Jipe_/DarkComet.yar \
                    yara-rules/Jipe_/Dotfuscator.yar \
                    yara-rules/Jipe_/Ice-IX.yar \
                    yara-rules/Jipe_/NetWiredRC_B.yar \
                    yara-rules/Jipe_/PlugX.yar \
                    yara-rules/Jipe_/Poisonivy.yar \
                    yara-rules/Jipe_/Qadars.yar \
                    yara-rules/Jipe_/Shylock.yar \
                    yara-rules/Jipe_/Spyeye.yar \
                    yara-rules/Jipe_/Swrort.yar \
                    yara-rules/Jipe_/Terminator.yar \
                    yara-rules/Jipe_/XTremRat.yar \
                    yara-rules/Jipe_/jRAT_conf.yar \
                    yara-rules/Jipe_/office_document_vba.yar \
                    yara-rules/Kevin_Falcoz/BlackShades_Trojan.yar \
                    yara-rules/Kevin_Falcoz/Bublik_Downloader.yar \
                    yara-rules/Kevin_Falcoz/Grozlex_Stealer.yar \
                    yara-rules/Kevin_Falcoz/Packers.yar \
                    yara-rules/Kevin_Falcoz/Wabot_Worm.yar \
                    yara-rules/Kevin_Falcoz/YahLover_Worm.yar \
                    yara-rules/Kevin_Falcoz/Zegost_Trojan.yar \
                    yara-rules/Kevin_Falcoz/lost_door_Trojan.yar \
                    yara-rules/Kevin_Falcoz/universal_1337_stealer_serveur.yar \
                    yara-rules/Kevin_Falcoz/xtreme_rat.yar \
                    yara-rules/LastLine/AgentTesla.yar \
                    yara-rules/M4r14ch1/Havex_NetScan.yar \
                    yara-rules/McAfee/CTB_Locker_Ransomware.yar \
                    yara-rules/McAfee/CredStealer.yar \
                    yara-rules/McAfee/CryptoLocker_rule2.yar \
                    yara-rules/McAfee/CryptoLocker_set1.yar \
                    yara-rules/McAfee/GPGQwerty_ransomware.yar \
                    yara-rules/McAfee/NionSpy.yar \
                    yara-rules/McAfee/OLE_JSRAT.yar \
                    yara-rules/McAfee/Spygate_2.9_RAT.yar \
                    yara-rules/McAfee/W97M_Vawtrak_dropper.yar \
                    yara-rules/McAfee/WannaCry.yar \
                    yara-rules/McAfee/kraken_ransomware.yar \
                    yara-rules/McAfee/rovnix_downloader.yar \
                    yara-rules/McAfee/shifu.yar \
                    yara-rules/Microsoft/Platinum.yara \
                    yara-rules/Mike_Schladt/apt_win_blackenergy3_core.yar \
                    yara-rules/Mike_Schladt/apt_win_blackenergy3_installer.yar \
                    yara-rules/Mikesxrs/ALFA_TEaM_Shell_V1.yar \
                    yara-rules/Mikesxrs/ALFA_TEaM_Shell_V2.yar \
                    yara-rules/Mikesxrs/APT3_PDB_Paths.yar \
                    yara-rules/Mikesxrs/AppleJeus_PDB.yar \
                    yara-rules/Mikesxrs/Aurora_PDB.yar \
                    yara-rules/Mikesxrs/BADPATCH_PDB.yar \
                    yara-rules/Mikesxrs/CN_group_PDB.yar \
                    yara-rules/Mikesxrs/Cleaver_PDB.yar \
                    yara-rules/Mikesxrs/FREEMILK_PDB.yar \
                    yara-rules/Mikesxrs/Final1stspy_PDB.yar \
                    yara-rules/Mikesxrs/GravityRAT_G1-GX.yar \
                    yara-rules/Mikesxrs/Greenbug_PDB.yar \
                    yara-rules/Mikesxrs/HTTPBrowser_PDB_Path.yar \
                    yara-rules/Mikesxrs/IRONGATE_SCADA.yar \
                    yara-rules/Mikesxrs/JRAT.yar \
                    yara-rules/Mikesxrs/KASPERAGENT_MICROPSIA_PDB.yar \
                    yara-rules/Mikesxrs/KONNI_PDB.yar \
                    yara-rules/Mikesxrs/Luckymouse_cert.yar \
                    yara-rules/Mikesxrs/Nitlove_PoS.yar \
                    yara-rules/Mikesxrs/OSX_XSL.yar \
                    yara-rules/Mikesxrs/PDB_Arachnophobia.yar \
                    yara-rules/Mikesxrs/Pirates.yar \
                    yara-rules/Mikesxrs/PlugX_PDB_Paths.yar \
                    yara-rules/Mikesxrs/Poisioned_Hurricane_Certs.yar \
                    yara-rules/Mikesxrs/REHASHED_PDB.yar \
                    yara-rules/Mikesxrs/Ratty.yar \
                    yara-rules/Mikesxrs/SAFFRON_ROSE_PDB_PATH.yar \
                    yara-rules/Mikesxrs/Sengoku_PDB.yar \
                    yara-rules/Mikesxrs/SyberSpace_PDB.yar \
                    yara-rules/Mikesxrs/Syrian_Malware_Team_Blackworm.yar \
                    yara-rules/Mikesxrs/TropicTrooper_keyboy_PDB.yar \
                    yara-rules/NCCGroup/APT15.yar \
                    yara-rules/NCCGroup/ISMRAT.yar \
                    yara-rules/NCCGroup/Sakula.yar \
                    yara-rules/NCCGroup/authenticode_anomalies.yara \
                    yara-rules/NCCGroup/badwinmail.yara \
                    yara-rules/NCCGroup/heartbleed.yar \
                    yara-rules/NCCGroup/package_manager.yara \
                    yara-rules/NCCGroup/redleaves.yar \
                    yara-rules/NCCGroup/turla_neuron_nautilus.yar \
                    yara-rules/NCSC/turla_neuron_nautilus.yar \
                    yara-rules/Nick_Hoffman/Check_Debugger.yar \
                    yara-rules/Nick_Hoffman/Check_Dlls.yar \
                    yara-rules/Nick_Hoffman/Check_DriveSize.yar \
                    yara-rules/Nick_Hoffman/Check_FilePaths.yar \
                    yara-rules/Nick_Hoffman/Check_Qemu_Description.yar \
                    yara-rules/Nick_Hoffman/Check_Qemu_DeviceMap.yar \
                    yara-rules/Nick_Hoffman/Check_UserNames.yar \
                    yara-rules/Nick_Hoffman/Check_VBox_Description.yar \
                    yara-rules/Nick_Hoffman/Check_VBox_DeviceMap.yar \
                    yara-rules/Nick_Hoffman/Check_VBox_GuestAdditions.yar \
                    yara-rules/Nick_Hoffman/Check_VBox_VideoDrivers.yar \
                    yara-rules/Nick_Hoffman/Check_VMWare.yar \
                    yara-rules/Nick_Hoffman/Check_VmTools.yar \
                    yara-rules/Nick_Hoffman/Check_Wine.yar \
                    yara-rules/Nick_Hoffman/Dropper_Hancitor.yar \
                    yara-rules/Nick_Hoffman/N3utrino.yar \
                    yara-rules/Nick_Hoffman/bernhardpos.yar \
                    yara-rules/Nick_Hoffman/korlia.yar \
                    yara-rules/Nick_Hoffman/logpos.yar \
                    yara-rules/Nick_Hoffman/mozart.yar \
                    yara-rules/Niels_Warnars/encoded_vbs.yar \
                    yara-rules/Niels_Warnars/office_filetype.yar \
                    yara-rules/Novetta/DeltaCharlie.yara \
                    yara-rules/Novetta/Derusbi_Server.yar \
                    yara-rules/Novetta/Hikit.yar \
                    yara-rules/Novetta/HotelAlfa.yara \
                    yara-rules/Novetta/IndiaAlfa.yara \
                    yara-rules/Novetta/IndiaBravo.yara \
                    yara-rules/Novetta/IndiaCharlie.yara \
                    yara-rules/Novetta/IndiaDelta.yara \
                    yara-rules/Novetta/IndiaEcho.yara \
                    yara-rules/Novetta/IndiaGolf.yara \
                    yara-rules/Novetta/IndiaHotel.yara \
                    yara-rules/Novetta/IndiaJuliett.yara \
                    yara-rules/Novetta/IndiaWhiskey.yara \
                    yara-rules/Novetta/KiloAlfa.yara \
                    yara-rules/Novetta/LimaAlfa.yara \
                    yara-rules/Novetta/LimaCharlie.yara \
                    yara-rules/Novetta/LimaDelta.yara \
                    yara-rules/Novetta/PapaAlfa.yara \
                    yara-rules/Novetta/RomeoAlfa.yara \
                    yara-rules/Novetta/RomeoBravo.yara \
                    yara-rules/Novetta/RomeoCharlie.yara \
                    yara-rules/Novetta/RomeoDelta.yara \
                    yara-rules/Novetta/RomeoEcho.yara \
                    yara-rules/Novetta/RomeoFoxtrot.yara \
                    yara-rules/Novetta/RomeoGolf.yara \
                    yara-rules/Novetta/RomeoHotel.yara \
                    yara-rules/Novetta/RomeoWhiskey.yara \
                    yara-rules/Novetta/SierraAlfa.yara \
                    yara-rules/Novetta/SierraBravo.yara \
                    yara-rules/Novetta/SierraCharlie.yara \
                    yara-rules/Novetta/SierraJuliettMikeOne.yara \
                    yara-rules/Novetta/SierraJuliettMikeTwo.yara \
                    yara-rules/Novetta/TangoAlfa.yara \
                    yara-rules/Novetta/TangoBravo.yara \
                    yara-rules/Novetta/UniformAlfa.yara \
                    yara-rules/Novetta/UniformJuliett.yara \
                    yara-rules/Novetta/WhiskeyAlfa.yara \
                    yara-rules/Novetta/WhiskeyBravo.yara \
                    yara-rules/Novetta/WhiskeyCharlie.yara \
                    yara-rules/Novetta/WhiskeyDelta.yara \
                    yara-rules/Novetta/cert_wiper.yara \
                    yara-rules/Novetta/general.yara \
                    yara-rules/Novetta/hidkit.yar \
                    yara-rules/Novetta/hikit.yar \
                    yara-rules/Novetta/hikit2.yar \
                    yara-rules/Novetta/mastersig.yara \
                    yara-rules/Novetta/sharedcode.yara \
                    yara-rules/Novetta/suicidescripts.yara \
                    yara-rules/Novetta/zox.yar \
                    yara-rules/PL_CERT/Madprotect_packer.yar \
                    yara-rules/PL_CERT/cryptomix_packer.yar \
                    yara-rules/PL_CERT/cryptomix_payload.yar \
                    yara-rules/PL_CERT/emotet.yara \
                    yara-rules/PL_CERT/kbot.yar \
                    yara-rules/PL_CERT/necurs.yar \
                    yara-rules/PL_CERT/nymaim.yar \
                    yara-rules/PL_CERT/ramnit.yar \
                    yara-rules/PL_CERT/sage.yar \
                    yara-rules/PWC/Elise_lstudio.yar \
                    yara-rules/PWC/Lightserver_variant_B.yar \
                    yara-rules/PWC/MSSUP.yar \
                    yara-rules/PWC/OrcaRAT.yar \
                    yara-rules/PWC/Tendrit_2014.yar \
                    yara-rules/PWC/smbWormTool.yar \
                    yara-rules/Pasquale_Stirparo/beef_hooked.yar \
                    yara-rules/Pasquale_Stirparo/beef_pretty_theft.yar \
                    yara-rules/RSA/Artifact_ORION_aPlib.yar \
                    yara-rules/RSA/Kingslayer_codekey.yar \
                    yara-rules/RSA/PNGRat.yar \
                    yara-rules/RSA/RTF_Shellcode.yar \
                    yara-rules/RSA/Squiblydoo.yar \
                    yara-rules/RSA/TROJAN_Notepad.yar \
                    yara-rules/RSA/Trojan_Derusbi.yar \
                    yara-rules/RSA/Trojan_Derusbi_AP32_Orion.yar \
                    yara-rules/RSA/Trojan_HIKIT.yar \
                    yara-rules/RSA/Trojan_Lurker2_ORION.yar \
                    yara-rules/RSA/liudoor.yar \
                    yara-rules/Rapid7/KeyBoy_Backdoor.yar \
                    yara-rules/Rapid7/KeyBoy_Dropper.yar \
                    yara-rules/Recorded_Future/ext4_linuxlistener.yar \
                    yara-rules/ReversingLabs/BadRabbitRansomware.yar \
                    yara-rules/ReversingLabs/CVE_2017_11882.yar \
                    yara-rules/ReversingLabs/obfuscated_dde.yar \
                    yara-rules/Root_9B/PoSLURP \
                    yara-rules/SadFud/DMALocker-All-Versions.yara \
                    yara-rules/SadFud/DMALocker4.0.yara \
                    yara-rules/SadFud/Remcos_RAT.yara \
                    yara-rules/SadFud/Ripper_ATM.yara \
                    yara-rules/SadFud/Satana_Ransomware.yara \
                    yara-rules/SadFud/Vbs-Obfuscated.yara \
                    yara-rules/SenseCy/ORXLocker.yar \
                    yara-rules/SenseCy/njrat_08d.yar \
                    yara-rules/Seth_Hardy/3102.yar \
                    yara-rules/Seth_Hardy/9002.yar \
                    yara-rules/Seth_Hardy/APT_NGO_wuaclt.yar \
                    yara-rules/Seth_Hardy/Babar.yar \
                    yara-rules/Seth_Hardy/GeorBot.yar \
                    yara-rules/Seth_Hardy/Scieron.yar \
                    yara-rules/Seth_Hardy/Swisyn.yar \
                    yara-rules/Seth_Hardy/Waterbug.yar \
                    yara-rules/Seth_Hardy/apt1.yar \
                    yara-rules/Seth_Hardy/bangat.yar \
                    yara-rules/Seth_Hardy/boouset.yar \
                    yara-rules/Seth_Hardy/comfoo.yar \
                    yara-rules/Seth_Hardy/cookies.yar \
                    yara-rules/Seth_Hardy/cxpid.yar \
                    yara-rules/Seth_Hardy/enfal.yar \
                    yara-rules/Seth_Hardy/ezcob.yar \
                    yara-rules/Seth_Hardy/f0xy.yar \
                    yara-rules/Seth_Hardy/fakem.yar \
                    yara-rules/Seth_Hardy/favorite.yar \
                    yara-rules/Seth_Hardy/glasses.yar \
                    yara-rules/Seth_Hardy/hangover.yar \
                    yara-rules/Seth_Hardy/iexpl0re.yar \
                    yara-rules/Seth_Hardy/imuler.yar \
                    yara-rules/Seth_Hardy/insta11.yar \
                    yara-rules/Seth_Hardy/kins.yar \
                    yara-rules/Seth_Hardy/leverage.yar \
                    yara-rules/Seth_Hardy/luckycat.yar \
                    yara-rules/Seth_Hardy/lurk0+cctv0.yar \
                    yara-rules/Seth_Hardy/maccontrol.yar \
                    yara-rules/Seth_Hardy/mask.yar \
                    yara-rules/Seth_Hardy/mirage.yar \
                    yara-rules/Seth_Hardy/mongal.yar \
                    yara-rules/Seth_Hardy/naikon.yar \
                    yara-rules/Seth_Hardy/naspyupdate.yar \
                    yara-rules/Seth_Hardy/nettraveler.yar \
                    yara-rules/Seth_Hardy/nsfree.yar \
                    yara-rules/Seth_Hardy/olyx.yar \
                    yara-rules/Seth_Hardy/plugx.yar \
                    yara-rules/Seth_Hardy/pubsab.yar \
                    yara-rules/Seth_Hardy/quarian.yar \
                    yara-rules/Seth_Hardy/regsubdat.yar \
                    yara-rules/Seth_Hardy/remote.yar \
                    yara-rules/Seth_Hardy/rookie.yar \
                    yara-rules/Seth_Hardy/rooter.yar \
                    yara-rules/Seth_Hardy/safenet.yar \
                    yara-rules/Seth_Hardy/scarhikn.yar \
                    yara-rules/Seth_Hardy/shell_crew.yar \
                    yara-rules/Seth_Hardy/surtr.yar \
                    yara-rules/Seth_Hardy/t5000.yar \
                    yara-rules/Seth_Hardy/urausy_skypedat.yar \
                    yara-rules/Seth_Hardy/vidgrab.yar \
                    yara-rules/Seth_Hardy/warp.yar \
                    yara-rules/Seth_Hardy/wimmie.yar \
                    yara-rules/Seth_Hardy/xtreme.yar \
                    yara-rules/Seth_Hardy/yayih.yar \
                    yara-rules/Spider-labs/apacheInjection.yara \
                    yara-rules/Spider-labs/cherryPicker.yar \
                    yara-rules/Spider-labs/punkey.yar \
                    yara-rules/Storm_Shield/AcidRain.yar \
                    yara-rules/Storm_Shield/AgentTesla.yar \
                    yara-rules/Tenable/Generic_JSP_Webshell.yar \
                    yara-rules/Tenable/Tenablebot.yar \
                    yara-rules/Tenable/UPX_PACKED.yar \
                    yara-rules/Tenable/cerber3.yar \
                    yara-rules/Tenable/elf_format.yar \
                    yara-rules/Tenable/fopo_webshell.yar \
                    yara-rules/Tenable/kaiten.yar \
                    yara-rules/Tenable/obfuscated_php.yar \
                    yara-rules/Tenable/pbot.yar \
                    yara-rules/Tenable/venom.yar \
                    yara-rules/Trend_Micro/PoS_Malware_MalumPOS.yar \
                    yara-rules/Trend_Micro/PoS_Malware_RawPOS2015_dumper.yar \
                    yara-rules/Trend_Micro/PoS_Malware_RawPOS2015_dumper_old.yar \
                    yara-rules/Trend_Micro/PoS_Malware_RawPOS2015_service.yar \
                    yara-rules/Trend_Micro/VBS.yar \
                    yara-rules/Trend_Micro/cracked_loki.yar \
                    yara-rules/Trend_Micro/crime_linux_umbreon_:_rootkit.yar \
                    yara-rules/US_CERT/Destructive_Hard_Drive_Tool.yar \
                    yara-rules/US_CERT/Destructive_Target_Cleaning_Tool.yar \
                    yara-rules/US_CERT/Destructive_Target_Cleaning_Tool_2.yar \
                    yara-rules/US_CERT/Destructive_Target_Cleaning_Tool_3.yar \
                    yara-rules/US_CERT/Destructive_Target_Cleaning_Tool_4.yar \
                    yara-rules/US_CERT/Destructive_Target_Cleaning_Tool_5.yar \
                    yara-rules/US_CERT/Destructive_Target_Cleaning_Tool_6.yar \
                    yara-rules/US_CERT/Destructive_Target_Cleaning_Tool_7.yar \
                    yara-rules/US_CERT/Destructive_Target_Cleaning_Tool_8.yar \
                    yara-rules/US_CERT/Dragonfly2.0.yar \
                    yara-rules/US_CERT/HIDDENCOBRA_RSA_MODULUS.yar \
                    yara-rules/US_CERT/HIDDEN_COBRA.yar \
                    yara-rules/US_CERT/Hidden_Cobra_DPRK_DDoS_Tool.yara \
                    yara-rules/US_CERT/Hidden_Cobra_Enfal.yar \
                    yara-rules/US_CERT/Lightweight_Backdoor.yar \
                    yara-rules/US_CERT/Lightweight_Backdoor_2.yar \
                    yara-rules/US_CERT/Lightweight_Backdoor_3.yar \
                    yara-rules/US_CERT/Lightweight_Backdoor_4.yar \
                    yara-rules/US_CERT/Lightweight_Backdoor_5.yar \
                    yara-rules/US_CERT/Lightweight_Backdoor_6.yar \
                    yara-rules/US_CERT/Malware_used_by_cyber_threat_actor_1.yar \
                    yara-rules/US_CERT/Malware_used_by_cyber_threat_actor_2.yar \
                    yara-rules/US_CERT/Malware_used_by_cyber_threat_actor_3.yar \
                    yara-rules/US_CERT/PAS_TOOL_PHP_WEB_KIT.yar \
                    yara-rules/US_CERT/Proxy_Tool.yar \
                    yara-rules/US_CERT/Proxy_Tool_2.yar \
                    yara-rules/US_CERT/Proxy_Tool_3.yar \
                    yara-rules/US_CERT/SMB_Worm_Tool.yar \
                    yara-rules/US_CERT/WannaCry.yara \
                    yara-rules/US_CERT/fallchill.yar \
                    yara-rules/US_CERT/hatman.yar \
                    yara-rules/VectraThreatLab/re.yar \
                    yara-rules/Vinsula/Vinsula_Sayad_Binder_infostealer.yar \
                    yara-rules/Vinsula/Vinsula_Sayad_Client_infostealer.yar \
                    yara-rules/Xecscan/Yarochkin.yar \
                    yara-rules/Xylitol/Malware.yar \
                    yara-rules/Xylitol/Zeus_1134.yar \
                    yara-rules/Xylitol/ibanking.yar \
                    yara-rules/Zerk_Labs/CVE_2012_0158_1.yar \
                    yara-rules/Zerk_Labs/Intel_Virtualization_Wizard.yar \
                    yara-rules/abhinavbom/APT.yara \
                    yara-rules/abhinavbom/Banbra-banker.yara \
                    yara-rules/abhinavbom/Duqu2-0.yara \
                    yara-rules/abhinavbom/XMLshell.yara \
                    yara-rules/abhinavbom/ghostRAT.yara \
                    yara-rules/abhinavbom/pos_malwares.yara \
                    yara-rules/abhinavbom/virustotal-rules.yara \
                    yara-rules/abhinavbom/vm-detect.yara \
                    yara-rules/adamburt/*nix_shellshock.yara \
                    yara-rules/adamburt/win_BackoffPOS.yara \
                    yara-rules/adamburt/win_Dexter.yara \
                    yara-rules/adamburt/win_metasploit_related.yara \
                    yara-rules/adamburt/win_trojan-poweliks-dropper.yara \
                    yara-rules/arbor/Athena.yar \
                    yara-rules/arbor/Black_Revolution_DDoS.yar \
                    yara-rules/arbor/Computrace.yar \
                    yara-rules/arbor/buhtrapknock.yar \
                    yara-rules/arbor/chicken.yar \
                    yara-rules/arbor/dirtjumper_drive.yar \
                    yara-rules/arbor/dirtjumper_drive2.yar \
                    yara-rules/arbor/dirtjumper_drive3.yar \
                    yara-rules/arbor/flusihoc.yar \
                    yara-rules/arbor/kivars_service.yar \
                    yara-rules/arbor/madness.yar \
                    yara-rules/ballastsecurity/alina.yara \
                    yara-rules/ballastsecurity/andromeda.yara \
                    yara-rules/ballastsecurity/athenahttp.yara \
                    yara-rules/ballastsecurity/backoff.yara \
                    yara-rules/ballastsecurity/blackshades.yara \
                    yara-rules/ballastsecurity/blackworm.yara \
                    yara-rules/ballastsecurity/cybergate.yara \
                    yara-rules/ballastsecurity/cythosia.yara \
                    yara-rules/ballastsecurity/darkcomet.yara \
                    yara-rules/ballastsecurity/dendroid.yara \
                    yara-rules/ballastsecurity/dexter.yara \
                    yara-rules/ballastsecurity/diamondfox.yara \
                    yara-rules/ballastsecurity/easterjackpos.yara \
                    yara-rules/ballastsecurity/elise.yara \
                    yara-rules/ballastsecurity/evora.yara \
                    yara-rules/ballastsecurity/genome.yara \
                    yara-rules/ballastsecurity/glassrat.yara \
                    yara-rules/ballastsecurity/herpes.yara \
                    yara-rules/ballastsecurity/jackpos.yara \
                    yara-rules/ballastsecurity/maazben.yara \
                    yara-rules/ballastsecurity/madnesspro.yar \
                    yara-rules/ballastsecurity/madnesspro.yara \
                    yara-rules/ballastsecurity/nanocore.yara \
                    yara-rules/ballastsecurity/njrat.yara \
                    yara-rules/ballastsecurity/pbot.yara \
                    yara-rules/ballastsecurity/poisonivy.yara \
                    yara-rules/ballastsecurity/pony.yara \
                    yara-rules/ballastsecurity/projecthook.yara \
                    yara-rules/ballastsecurity/solarbot.yara \
                    yara-rules/ballastsecurity/vertexnet.yara \
                    yara-rules/ballastsecurity/vskimmer.yara \
                    yara-rules/ballastsecurity/xtreme.yara \
                    yara-rules/bluecoat/InceptionBlackberry.yar \
                    yara-rules/bluecoat/InceptionDLL.yar \
                    yara-rules/bluecoat/InceptionIOS.yar \
                    yara-rules/bluecoat/InceptionMips.yar \
                    yara-rules/bluecoat/InceptionRTF.yar \
                    yara-rules/bluecoat/InceptionVBS.yar \
                    yara-rules/blueliv/WannaCryptor.yar \
                    yara-rules/blueliv/petya_eternalblue.yar \
                    yara-rules/carbon_black/DPRK_ROKRAT.yar \
                    yara-rules/carbon_black/PNG_dropper.yar \
                    yara-rules/carbon_black/Plugx.yar \
                    yara-rules/carbon_black/emotet.yar \
                    yara-rules/clamsrch_signatures/signsrch.yar \
                    yara-rules/clearskysec/gholee.yar \
                    yara-rules/codewatchorg/angler_ek_checkpoint.yar \
                    yara-rules/codewatchorg/angler_ek_redirector.yar \
                    yara-rules/codewatchorg/angler_flash.yar \
                    yara-rules/codewatchorg/angler_flash2.yar \
                    yara-rules/codewatchorg/angler_flash4.yar \
                    yara-rules/codewatchorg/angler_flash5.yar \
                    yara-rules/codewatchorg/angler_flash_uncompressed.yar \
                    yara-rules/codewatchorg/angler_html.yar \
                    yara-rules/codewatchorg/angler_html2.yar \
                    yara-rules/codewatchorg/angler_jar.yar \
                    yara-rules/codewatchorg/angler_js.yar \
                    yara-rules/codewatchorg/blackhole1_jar.yar \
                    yara-rules/codewatchorg/blackhole2_css.yar \
                    yara-rules/codewatchorg/blackhole2_htm.yar \
                    yara-rules/codewatchorg/blackhole2_htm10.yar \
                    yara-rules/codewatchorg/blackhole2_htm11.yar \
                    yara-rules/codewatchorg/blackhole2_htm12.yar \
                    yara-rules/codewatchorg/blackhole2_htm3.yar \
                    yara-rules/codewatchorg/blackhole2_htm5.yar \
                    yara-rules/codewatchorg/blackhole2_htm6.yar \
                    yara-rules/codewatchorg/blackhole2_htm8.yar \
                    yara-rules/codewatchorg/blackhole2_jar.yar \
                    yara-rules/codewatchorg/blackhole2_jar2.yar \
                    yara-rules/codewatchorg/blackhole2_jar3.yar \
                    yara-rules/codewatchorg/blackhole2_pdf.yar \
                    yara-rules/codewatchorg/bleedinglife2_adobe_2010_1297_exploit.yar \
                    yara-rules/codewatchorg/bleedinglife2_adobe_2010_2884_exploit.yar \
                    yara-rules/codewatchorg/bleedinglife2_jar2.yar \
                    yara-rules/codewatchorg/bleedinglife2_java_2010_0842_exploit.yar \
                    yara-rules/codewatchorg/crimepack_jar.yar \
                    yara-rules/codewatchorg/crimepack_jar3.yar \
                    yara-rules/codewatchorg/cve_2013_0074.yar \
                    yara-rules/codewatchorg/cve_2013_0422.yar \
                    yara-rules/codewatchorg/eleonore_jar.yar \
                    yara-rules/codewatchorg/eleonore_jar2.yar \
                    yara-rules/codewatchorg/eleonore_jar3.yar \
                    yara-rules/codewatchorg/eleonore_js.yar \
                    yara-rules/codewatchorg/eleonore_js2.yar \
                    yara-rules/codewatchorg/eleonore_js3.yar \
                    yara-rules/codewatchorg/fragus_htm.yar \
                    yara-rules/codewatchorg/fragus_js.yar \
                    yara-rules/codewatchorg/fragus_js2.yar \
                    yara-rules/codewatchorg/fragus_js_flash.yar \
                    yara-rules/codewatchorg/fragus_js_java.yar \
                    yara-rules/codewatchorg/fragus_js_quicktime.yar \
                    yara-rules/codewatchorg/fragus_js_vml.yar \
                    yara-rules/codewatchorg/javascript_exploit_and_obfuscation.yar \
                    yara-rules/codewatchorg/malicious_office.yar \
                    yara-rules/codewatchorg/phoenix_html.yar \
                    yara-rules/codewatchorg/phoenix_html10.yar \
                    yara-rules/codewatchorg/phoenix_html11.yar \
                    yara-rules/codewatchorg/phoenix_html2.yar \
                    yara-rules/codewatchorg/phoenix_html3.yar \
                    yara-rules/codewatchorg/phoenix_html4.yar \
                    yara-rules/codewatchorg/phoenix_html5.yar \
                    yara-rules/codewatchorg/phoenix_html6.yar \
                    yara-rules/codewatchorg/phoenix_html7.yar \
                    yara-rules/codewatchorg/phoenix_html8.yar \
                    yara-rules/codewatchorg/phoenix_html9.yar \
                    yara-rules/codewatchorg/phoenix_jar.yar \
                    yara-rules/codewatchorg/phoenix_jar2.yar \
                    yara-rules/codewatchorg/phoenix_jar3.yar \
                    yara-rules/codewatchorg/phoenix_pdf.yar \
                    yara-rules/codewatchorg/phoenix_pdf2.yar \
                    yara-rules/codewatchorg/phoenix_pdf3.yar \
                    yara-rules/codewatchorg/redkit_bin_basic.yar \
                    yara-rules/codewatchorg/sakura_jar.yar \
                    yara-rules/codewatchorg/sakura_jar2.yar \
                    yara-rules/codewatchorg/zeroaccess_css.yar \
                    yara-rules/codewatchorg/zeroaccess_css2.yar \
                    yara-rules/codewatchorg/zeroaccess_htm.yar \
                    yara-rules/codewatchorg/zeroaccess_js.yar \
                    yara-rules/codewatchorg/zeroaccess_js2.yar \
                    yara-rules/codewatchorg/zeroaccess_js3.yar \
                    yara-rules/codewatchorg/zeroaccess_js4.yar \
                    yara-rules/codewatchorg/zerox88_js2.yar \
                    yara-rules/codewatchorg/zerox88_js3.yar \
                    yara-rules/codewatchorg/zeus_js.yar \
                    yara-rules/contextis/Trojan_W32_Gh0stMiancha_1_0_0.yar \
                    yara-rules/crowdstrike/CVE_2014_4113.yar \
                    yara-rules/crowdstrike/CrowdStrike_CSIT_14003_03.yar \
                    yara-rules/crowdstrike/CrowdStrike_CSIT_14004_02.yar \
                    yara-rules/crowdstrike/CrowdStrike_FlyingKitten.yar \
                    yara-rules/crowdstrike/CrowdStrike_PutterPanda_01_-_fourh_stack_strings_putterpanda.yar \
                    yara-rules/crowdstrike/CrowdStrike__PutterPanda__02_-_rc4_dropper_putterpanda.yar \
                    yara-rules/crowdstrike/CrowdStrike__PutterPanda__03_-_threepara_para_implant_putterpanda.yar \
                    yara-rules/crowdstrike/CrowdStrike__PutterPanda__05_:_httpclient_putterpanda.yar \
                    yara-rules/crowdstrike/CrowdStrike__PutterPanda__06_:_xor_dropper_putterpanda.yar \
                    yara-rules/crowdstrike/gameover_zeus.yar \
                    yara-rules/crowdstrike/rule_CrowdStrike_PutterPanda_04:_pngdowner_putterpanda.yar \
                    yara-rules/crysys/duqu2.yar \
                    yara-rules/cylance/BackDoorLogger.yar \
                    yara-rules/cylance/Hkdoor_DLL.yar \
                    yara-rules/cylance/Hkdoor_backdoor.yar \
                    yara-rules/cylance/Hkdoor_driver.yar \
                    yara-rules/cylance/Hkdoor_dropper.yar \
                    yara-rules/cylance/Jasus.yar \
                    yara-rules/cylance/LoggerModule.yar \
                    yara-rules/cylance/MiSType_Backdoor_Packed.yar \
                    yara-rules/cylance/Misdat_Backdoor.yar \
                    yara-rules/cylance/Misdat_Backdoor_Packed.yar \
                    yara-rules/cylance/NetC.yar \
                    yara-rules/cylance/SType_Backdoor.yar \
                    yara-rules/cylance/ShellCreator2.yar \
                    yara-rules/cylance/SmartCopy2.yar \
                    yara-rules/cylance/SynFlooder.yar \
                    yara-rules/cylance/TinyZBot.yar \
                    yara-rules/cylance/WannaCryptor.yar \
                    yara-rules/cylance/ZhoupinExploitCrew.yar \
                    yara-rules/cylance/Zlib_Backdoor.yar \
                    yara-rules/cylance/antivirusdetector.yar \
                    yara-rules/cylance/csext.yar \
                    yara-rules/cylance/kagent.yar \
                    yara-rules/cylance/mimikatzWrapper.yar \
                    yara-rules/cylance/pvz_in.yar \
                    yara-rules/cylance/pvz_out.yar \
                    yara-rules/cylance/wndTest.yar \
                    yara-rules/cylance/zhCat.yar \
                    yara-rules/cylance/zhLookUp.yar \
                    yara-rules/cylance/zhmimikatz.yar \
                    yara-rules/dragos/Crashoverride.yara \
                    yara-rules/eset/Animal_Farm.yar \
                    yara-rules/eset/Linux_Moose.yar \
                    yara-rules/eset/Mumblehard_packer.yar \
                    yara-rules/eset/OSX_Keydnap_backdoor.yar \
                    yara-rules/eset/OSX_Keydnap_packer.yar \
                    yara-rules/eset/OSX_keydnap_downloader.yar \
                    yara-rules/eset/Operation_Potao.yar \
                    yara-rules/eset/Operation_Windigo.yar \
                    yara-rules/eset/linux_rakos.yar \
                    yara-rules/evild3ad_/contains_ah_encoded_pe_file.yara \
                    yara-rules/evild3ad_/contains_ascii_hex_encoded_pe_file.yara \
                    yara-rules/evild3ad_/contains_hidden_pe_file_inside_a_sequence_of_numbers.yara \
                    yara-rules/evild3ad_/contains_userform_object_1.yara \
                    yara-rules/evild3ad_/contains_userform_object_2.yara \
                    yara-rules/evild3ad_/contains_userform_object_3.yara \
                    yara-rules/evild3ad_/contains_vba_macro_code.yara \
                    yara-rules/evild3ad_/mime_mso_activemime_base64.yara \
                    yara-rules/forcepoint/CVE_2014_6352.yar \
                    yara-rules/forcepoint/Zbot.yar \
                    yara-rules/forcepoint/f0xy.yar \
                    yara-rules/fox-it/rule_Ponmocup_plugins.yar \
                    yara-rules/fox-it/shimrat.yar \
                    yara-rules/fox-it/shimratreporter.yar \
                    yara-rules/g00dv1n/Adware.AdGazelle.yar \
                    yara-rules/g00dv1n/Adware.Adpeak.yar \
                    yara-rules/g00dv1n/Adware.Agent.yar \
                    yara-rules/g00dv1n/Adware.BetterSurf.yar \
                    yara-rules/g00dv1n/Adware.BrowseFox.yar \
                    yara-rules/g00dv1n/Adware.Conduit.yar \
                    yara-rules/g00dv1n/Adware.ConvertAd.yar \
                    yara-rules/g00dv1n/Adware.Crossrider.yar \
                    yara-rules/g00dv1n/Adware.DealPly.yar \
                    yara-rules/g00dv1n/Adware.Dlhelper.yar \
                    yara-rules/g00dv1n/Adware.Downloader.yar \
                    yara-rules/g00dv1n/Adware.ELEX.yar \
                    yara-rules/g00dv1n/Adware.Gen.yar \
                    yara-rules/g00dv1n/Adware.Genieo.yar \
                    yara-rules/g00dv1n/Adware.Imali.yar \
                    yara-rules/g00dv1n/Adware.InstallCore.yar \
                    yara-rules/g00dv1n/Adware.Linkury.yar \
                    yara-rules/g00dv1n/Adware.MyWebSearch.yar \
                    yara-rules/g00dv1n/Adware.NextLive.yar \
                    yara-rules/g00dv1n/Adware.ObronaAds.yar \
                    yara-rules/g00dv1n/Adware.OpenCandy.yar \
                    yara-rules/g00dv1n/Adware.OutBrowse.yar \
                    yara-rules/g00dv1n/Adware.PullUpdate.yar \
                    yara-rules/g00dv1n/Adware.SProtect.yar \
                    yara-rules/g00dv1n/Adware.SearchSuite.yar \
                    yara-rules/g00dv1n/Adware.Sendori.yar \
                    yara-rules/g00dv1n/Adware.SimplyTech.yar \
                    yara-rules/g00dv1n/Adware.SmartApps.yar \
                    yara-rules/g00dv1n/Adware.Solimbda.yar \
                    yara-rules/g00dv1n/Adware.Trioris.yar \
                    yara-rules/g00dv1n/Adware.Vitruvian.yar \
                    yara-rules/g00dv1n/Adware.Wajam.yar \
                    yara-rules/g00dv1n/Adware.WebTools.yar \
                    yara-rules/g00dv1n/Adware.WebWatcher.yar \
                    yara-rules/g00dv1n/Adware.iBryte.yar \
                    yara-rules/g00dv1n/Adware.uKor.yar \
                    yara-rules/g00dv1n/Backdoor.Bladabindi.yar \
                    yara-rules/g00dv1n/Backdoor.Dedipros.yar \
                    yara-rules/g00dv1n/Backdoor.Fynloski.yar \
                    yara-rules/g00dv1n/Backdoor.Gen.yar \
                    yara-rules/g00dv1n/Backdoor.Liudoor.yar \
                    yara-rules/g00dv1n/Backdoor.Mirage.yar \
                    yara-rules/g00dv1n/Backdoor.Vawtrak.yar \
                    yara-rules/g00dv1n/Backdoor.Zegost.yar \
                    yara-rules/g00dv1n/Malware.BitCoinMiner.yar \
                    yara-rules/g00dv1n/Malware.Downloader.yar \
                    yara-rules/g00dv1n/Malware.PWS.yar \
                    yara-rules/g00dv1n/PUP.SystemOptimizer.yar \
                    yara-rules/g00dv1n/PUP.Systweak.yar \
                    yara-rules/g00dv1n/Risk.DetectAnalysis.yar \
                    yara-rules/g00dv1n/Risk.NetFilter.yar \
                    yara-rules/g00dv1n/Rogue.AVSoft.yar \
                    yara-rules/g00dv1n/Rogue.Braviax.yar \
                    yara-rules/g00dv1n/Rogue.FakePAV.yar \
                    yara-rules/g00dv1n/Rogue.FakeRean.yar \
                    yara-rules/g00dv1n/Rogue.FakeSysDef.yar \
                    yara-rules/g00dv1n/Rogue.LiveSP.yar \
                    yara-rules/g00dv1n/Rogue.SDef.yar \
                    yara-rules/g00dv1n/Rogue.SysDoc.yar \
                    yara-rules/g00dv1n/Rogue.Winwebsec.yar \
                    yara-rules/g00dv1n/Trojan.Antivar.yar \
                    yara-rules/g00dv1n/Trojan.Cbeplay.yar \
                    yara-rules/g00dv1n/Trojan.ChStartPage.yar \
                    yara-rules/g00dv1n/Trojan.Citadel.yar \
                    yara-rules/g00dv1n/Trojan.Comfoo.yar \
                    yara-rules/g00dv1n/Trojan.Cutwail.yar \
                    yara-rules/g00dv1n/Trojan.Dllpatcher.yar \
                    yara-rules/g00dv1n/Trojan.Downloader.yar \
                    yara-rules/g00dv1n/Trojan.Dropper.yar \
                    yara-rules/g00dv1n/Trojan.Frethog.yar \
                    yara-rules/g00dv1n/Trojan.GBot.yar \
                    yara-rules/g00dv1n/Trojan.Gamarue.Andromeda.yar \
                    yara-rules/g00dv1n/Trojan.Injector.yar \
                    yara-rules/g00dv1n/Trojan.Kovter.yar \
                    yara-rules/g00dv1n/Trojan.Kuluoz.yar \
                    yara-rules/g00dv1n/Trojan.Lethic.yar \
                    yara-rules/g00dv1n/Trojan.Necurs.yar \
                    yara-rules/g00dv1n/Trojan.Nedsym.yar \
                    yara-rules/g00dv1n/Trojan.Neurevt.yar \
                    yara-rules/g00dv1n/Trojan.PowerLoader.yar \
                    yara-rules/g00dv1n/Trojan.Ransom.yar \
                    yara-rules/g00dv1n/Trojan.Regin.yar \
                    yara-rules/g00dv1n/Trojan.Rovnix.yar \
                    yara-rules/g00dv1n/Trojan.Simda.yar \
                    yara-rules/g00dv1n/Trojan.Sirefef.yar \
                    yara-rules/g00dv1n/Trojan.Upatre.yar \
                    yara-rules/g00dv1n/Trojan.Virtool.Obfuscator.yar \
                    yara-rules/g00dv1n/TrojanPSW.Tepfer.yar \
                    yara-rules/g00dv1n/TrojanPSW.ZBot.yar \
                    yara-rules/g00dv1n/TrojanSpy.Ursnif.yar \
                    yara-rules/g00dv1n/Virus.Chir.yar \
                    yara-rules/g00dv1n/Virus.Madang.yar \
                    yara-rules/g00dv1n/Worm.Cridex.yar \
                    yara-rules/g00dv1n/Worm.Dorkbot.yar \
                    yara-rules/g00dv1n/Worm.Phorpiex.yar \
                    yara-rules/g00dv1n/Worm.SillyP2P.yar \
                    yara-rules/g00dv1n/Worm.SkypeSpamer.yar \
                    yara-rules/group-ib/CorkowDLL.yar \
                    yara-rules/hidd3ncod3s/trojan_win_dridex.yar \
                    yara-rules/iDefense/WannaCrypt0r.yara \
                    yara-rules/iocbucket/APT_NGO_wuaclt_PDF.yar \
                    yara-rules/iocbucket/apt_ngo_wuaclt.yar \
                    yara-rules/jackcr/gh0st.yar \
                    yara-rules/jackcr/pivy.yar \
                    yara-rules/jackcr/shylock.yar \
                    yara-rules/kaspersky/Adwind.yar \
                    yara-rules/kaspersky/Crime_eyepyramid.yar \
                    yara-rules/kaspersky/LazarusWannaCry.yar \
                    yara-rules/kaspersky/apt_ProjectSauron_MyTrampoline.yar \
                    yara-rules/kaspersky/apt_ProjectSauron_encrypted_LSA.yar \
                    yara-rules/kaspersky/apt_ProjectSauron_encrypted_SSPI.yar \
                    yara-rules/kaspersky/apt_ProjectSauron_encrypted_container.yar \
                    yara-rules/kaspersky/apt_ProjectSauron_encryption.yar \
                    yara-rules/kaspersky/apt_ProjectSauron_generic_pipe_backdoor.yar \
                    yara-rules/kaspersky/apt_ProjectSauron_pipe_backdoor.yar \
                    yara-rules/kaspersky/apt_duqu2_drivers.yar \
                    yara-rules/kaspersky/apt_duqu2_loaders.yar \
                    yara-rules/kaspersky/apt_equation_cryptotable.yar \
                    yara-rules/kaspersky/apt_equation_doublefantasy_genericresource.yar \
                    yara-rules/kaspersky/apt_equation_equationlaser_runtimeclasses.yar \
                    yara-rules/kaspersky/apt_equation_exploitlib_mutexes.yar \
                    yara-rules/kaspersky/apt_hellsing_implantstrings.yar \
                    yara-rules/kaspersky/apt_hellsing_installer.yar \
                    yara-rules/kaspersky/apt_hellsing_irene.yar \
                    yara-rules/kaspersky/apt_hellsing_msgertype2.yar \
                    yara-rules/kaspersky/apt_hellsing_proxytool.yar \
                    yara-rules/kaspersky/apt_hellsing_xkat.yar \
                    yara-rules/kaspersky/apt_regin_2013_64bit_stage1.yar \
                    yara-rules/kaspersky/apt_regin_dispatcher_disp_dll.yar \
                    yara-rules/kaspersky/apt_regin_vfs.yar \
                    yara-rules/kaspersky/backdoored_ssh.yar \
                    yara-rules/kaspersky/exploit_Silverlight_Toropov_Generic_XAP.yar \
                    yara-rules/kaspersky/ransomware_PetrWrap.yar \
                    yara-rules/kaspersky/stonedrill.yar \
                    yara-rules/kaspersky/xDedic_SysScan_unpacked.yar \
                    yara-rules/kaspersky/xdedic_packed_syscan.yar \
                    yara-rules/kevthehermit/AAR.yar \
                    yara-rules/kevthehermit/Adzok.yar \
                    yara-rules/kevthehermit/AlienSpy.yar \
                    yara-rules/kevthehermit/Ap0calypse.yar \
                    yara-rules/kevthehermit/Arcom.yar \
                    yara-rules/kevthehermit/Bandook.yar \
                    yara-rules/kevthehermit/BlackNix.yar \
                    yara-rules/kevthehermit/BlackShades.yar \
                    yara-rules/kevthehermit/BlueBanana.yar \
                    yara-rules/kevthehermit/Bozok.yar \
                    yara-rules/kevthehermit/ClientMesh.yar \
                    yara-rules/kevthehermit/Crimson.yar \
                    yara-rules/kevthehermit/CyberGate.yar \
                    yara-rules/kevthehermit/DarkComet.yar \
                    yara-rules/kevthehermit/DarkRAT.yar \
                    yara-rules/kevthehermit/Greame.yar \
                    yara-rules/kevthehermit/Hangover_ron_babylon.yar \
                    yara-rules/kevthehermit/HawkEye.yar \
                    yara-rules/kevthehermit/Imminent3.yar \
                    yara-rules/kevthehermit/Infinity.yar \
                    yara-rules/kevthehermit/JavaDropper.yar \
                    yara-rules/kevthehermit/LostDoor.yar \
                    yara-rules/kevthehermit/LuminosityLink.yar \
                    yara-rules/kevthehermit/LuxNet.yar \
                    yara-rules/kevthehermit/NanoCore.yar \
                    yara-rules/kevthehermit/NetWire.yar \
                    yara-rules/kevthehermit/Pandora.yar \
                    yara-rules/kevthehermit/Paradox.yar \
                    yara-rules/kevthehermit/PoisonIvy.yar \
                    yara-rules/kevthehermit/Punisher.yar \
                    yara-rules/kevthehermit/PythoRAT.yar \
                    yara-rules/kevthehermit/ShadowTech.yar \
                    yara-rules/kevthehermit/SmallNet.yar \
                    yara-rules/kevthehermit/SpyGate.yar \
                    yara-rules/kevthehermit/Sub7Nation.yar \
                    yara-rules/kevthehermit/Vertex.yar \
                    yara-rules/kevthehermit/VirusRat.yar \
                    yara-rules/kevthehermit/Xena.yar \
                    yara-rules/kevthehermit/Xtreme.yar \
                    yara-rules/kevthehermit/adWind.yar \
                    yara-rules/kevthehermit/jRat.yar \
                    yara-rules/kevthehermit/njRat.yar \
                    yara-rules/kevthehermit/unrecom.yar \
                    yara-rules/kevthehermit/xRAT.yar \
                    yara-rules/malc0de/auriga_apt1.yar \
                    yara-rules/malc0de/bouncer2_exe_apt1.yar \
                    yara-rules/malc0de/bouncer_dll_apt1.yar \
                    yara-rules/malc0de/bouncer_exe_apt1.yar \
                    yara-rules/malc0de/calendar_apt1.yar \
                    yara-rules/malc0de/combos_apt1.yar \
                    yara-rules/malc0de/cookiebag_apt1.yar \
                    yara-rules/malc0de/dairy_apt1.yar \
                    yara-rules/malc0de/gdocupload_apt1.yar \
                    yara-rules/malc0de/getmail_apt1.yar \
                    yara-rules/malc0de/glooxmail_apt1.yar \
                    yara-rules/malc0de/goggles_apt1.yar \
                    yara-rules/malc0de/greencat_apt1.yar \
                    yara-rules/malc0de/hacksfase_apt1.yar \
                    yara-rules/malc0de/helauto_apt.yar \
                    yara-rules/malc0de/kurton_apt1.yar \
                    yara-rules/malc0de/lightbolt_apt1.yar \
                    yara-rules/malc0de/lightdart_apt1.yar \
                    yara-rules/malc0de/longrun_apt1.yar \
                    yara-rules/malc0de/macromail_apt1.yar \
                    yara-rules/malc0de/manitsme_apt1.yar \
                    yara-rules/malc0de/mapiget_apt1.yar \
                    yara-rules/malc0de/miniasp_apt1.yar \
                    yara-rules/malc0de/newsreels_apt1.yar \
                    yara-rules/malc0de/seasalt_apt1.yar \
                    yara-rules/malc0de/starsypound_apt1.yar \
                    yara-rules/malc0de/sword_apt1.yar \
                    yara-rules/malc0de/tabmsgsql_apt1.yar \
                    yara-rules/malc0de/tarsip_apt1.yar \
                    yara-rules/malc0de/tarsip_eclipse_apt1.yar \
                    yara-rules/malc0de/warp_apt1.yar \
                    yara-rules/malc0de/webc2_adspace_apt1.yar \
                    yara-rules/malc0de/webc2_ausov_apt1.yar \
                    yara-rules/malc0de/webc2_bolid_apt1.yar \
                    yara-rules/malc0de/webc2_clover_apt1.yar \
                    yara-rules/malc0de/webc2_cson_apt.yar \
                    yara-rules/malc0de/webc2_div_apt1.yar \
                    yara-rules/malc0de/webc2_greencat_apt1.yar \
                    yara-rules/malc0de/webc2_head_apt1.yar \
                    yara-rules/malc0de/webc2_kt3_apt1.yar \
                    yara-rules/malc0de/webc2_qbp_apt1.yar \
                    yara-rules/malc0de/webc2_rave_apt1.yar \
                    yara-rules/malc0de/webc2_table_apt1.yar \
                    yara-rules/malc0de/webc2_ugx_apt1.yar \
                    yara-rules/malc0de/webc2_y21k_apt1.yar \
                    yara-rules/malc0de/webc2_yahoo_apt1.yar \
                    yara-rules/malwarebytes/MonkerTrojan.yar \
                    yara-rules/malwarebytes/zeroaccess.yar \
                    yara-rules/malwarecookbook/packer.yara \
                    yara-rules/malwaretracker/apt_actor_tran_duy_linh.yar \
                    yara-rules/malwaretracker/doc_zws_flash.yar \
                    yara-rules/malwaretracker/mime_mso.yar \
                    yara-rules/mimikatz/kiwi_passwords.yar \
                    yara-rules/n3sfox/Tinba2.yar \
                    yara-rules/naxonez/DebuggerCheck.yar \
                    yara-rules/netlab360/elknot_billgates.yar \
                    yara-rules/nex/embedded_macho.yar \
                    yara-rules/nex/embedded_pe.yar \
                    yara-rules/nex/embedded_win_api.yar \
                    yara-rules/nex/shellcode.yar \
                    yara-rules/nex/vm_detect.yar \
                    yara-rules/nshadov/RANSOMWARE_RAA.yar \
                    yara-rules/one_offs/9002Rat.yar \
                    yara-rules/one_offs/CVE-2013-3660.yar \
                    yara-rules/one_offs/ComputraceAgent.yar \
                    yara-rules/one_offs/CoreFlood_ldr.yar \
                    yara-rules/one_offs/Cridex.yar \
                    yara-rules/one_offs/Hancidoc_Dropper.yar \
                    yara-rules/one_offs/Mebroot_Torpig.yar \
                    yara-rules/one_offs/OSX_Malware.yar \
                    yara-rules/one_offs/Pegasus.yar \
                    yara-rules/one_offs/Qadars_DGA.yar \
                    yara-rules/one_offs/Shellphish.yar \
                    yara-rules/one_offs/W32ChirB.yar \
                    yara-rules/one_offs/XorDDoS.yar \
                    yara-rules/one_offs/ammyy_cerber3.yar \
                    yara-rules/one_offs/crime_ole_loadswf_cve_2018_4878.yar \
                    yara-rules/one_offs/crime_win32_gratefulpos_trojan.yar \
                    yara-rules/one_offs/fastposloader.yar \
                    yara-rules/one_offs/marcher.yar \
                    yara-rules/one_offs/mwi_document.yar \
                    yara-rules/one_offs/nettraveler.yar \
                    yara-rules/one_offs/packager_cve2017_11882.yar \
                    yara-rules/one_offs/snake_uroburos.yar \
                    yara-rules/openanalysis/andromeda.yara \
                    yara-rules/optiv/autoit_scripting_pos_malware.yar \
                    yara-rules/paloalto/ce_enfal_cmstar_debug_msg.yar \
                    yara-rules/paloalto/cobalt_gang_builder.yar \
                    yara-rules/paloalto/hancitor_dropper.yar \
                    yara-rules/paloalto/hancitor_payload.yar \
                    yara-rules/paloalto/hancitor_stage1.yar \
                    yara-rules/paloalto/powerstager.yar \
                    yara-rules/patrickrolsen/Armadillo_v1xx__v2xx.yar \
                    yara-rules/patrickrolsen/Backdoor_APT_Mongall.yar \
                    yara-rules/patrickrolsen/CVE_2013_1347.yar \
                    yara-rules/patrickrolsen/GIF_exploit.yar \
                    yara-rules/patrickrolsen/LNK_files.yar \
                    yara-rules/patrickrolsen/PCAPs.yar \
                    yara-rules/patrickrolsen/UPX_290_LZMA.yar \
                    yara-rules/patrickrolsen/UPX_Protector_v10x_2.yar \
                    yara-rules/patrickrolsen/UPX_V200V290.yar \
                    yara-rules/patrickrolsen/UPX_v0896.yar \
                    yara-rules/patrickrolsen/acunetix_web_scanner.yar \
                    yara-rules/patrickrolsen/bcp_sql_tool.yar \
                    yara-rules/patrickrolsen/beep_remote_shell.yar \
                    yara-rules/patrickrolsen/blat_email_301.yar \
                    yara-rules/patrickrolsen/blazingtools.yar \
                    yara-rules/patrickrolsen/cmd_shell.yar \
                    yara-rules/patrickrolsen/dark_edition.yar \
                    yara-rules/patrickrolsen/dump_tool.yar \
                    yara-rules/patrickrolsen/gsec_generic.yar \
                    yara-rules/patrickrolsen/html_exploit_GIF.yar \
                    yara-rules/patrickrolsen/jpg_web_shell.yar \
                    yara-rules/patrickrolsen/keyfinder_tool.yar \
                    yara-rules/patrickrolsen/luxnet.yar \
                    yara-rules/patrickrolsen/misc_iocs.yar \
                    yara-rules/patrickrolsen/misc_php_exploits.yar \
                    yara-rules/patrickrolsen/misc_shells.yar \
                    yara-rules/patrickrolsen/monitor_tool_pos.yar \
                    yara-rules/patrickrolsen/mpress_2_xx_net_:_Packer.yar \
                    yara-rules/patrickrolsen/mpress_2_xx_x64_:_Packer.yar \
                    yara-rules/patrickrolsen/mpress_2_xx_x86_:_Packer.yar \
                    yara-rules/patrickrolsen/nbtscan.yar \
                    yara-rules/patrickrolsen/osql_tool.yar \
                    yara-rules/patrickrolsen/port_forward_tool.yar \
                    yara-rules/patrickrolsen/pos_malware.yar \
                    yara-rules/patrickrolsen/pos_memory.yar \
                    yara-rules/patrickrolsen/pos_memory_scrapper.yar \
                    yara-rules/patrickrolsen/procdump.yar \
                    yara-rules/patrickrolsen/psexec_generic.yar \
                    yara-rules/patrickrolsen/pstgdump.yar \
                    yara-rules/patrickrolsen/rtf_Kaba_jDoe.yar \
                    yara-rules/patrickrolsen/rtf_multiple.yar \
                    yara-rules/patrickrolsen/rtf_yahoo_ken.yar \
                    yara-rules/patrickrolsen/rule__Armadillo_v171 \
                    yara-rules/patrickrolsen/scanline_mcafee.yar \
                    yara-rules/patrickrolsen/seven_zip_cmdversion.yar \
                    yara-rules/patrickrolsen/shell_functions.yar \
                    yara-rules/patrickrolsen/shell_names.yar \
                    yara-rules/patrickrolsen/sneakernet_trojan.yar \
                    yara-rules/patrickrolsen/tran_duy_linh.yar \
                    yara-rules/patrickrolsen/unknown_creds_dump.yar \
                    yara-rules/patrickrolsen/web_log_review.yar \
                    yara-rules/patrickrolsen/web_shell_crews.yar \
                    yara-rules/patrickrolsen/winrar_4xx.yar \
                    yara-rules/patrickrolsen/wp_shell.yar \
                    yara-rules/patrickrolsen/zend_framework.yar \
                    yara-rules/phbiohazard/APT20140414_1NT.yar \
                    yara-rules/phbiohazard/APT20140414_1PE.yar \
                    yara-rules/phbiohazard/ID2015032010000026.yar \
                    yara-rules/phish_me/Cryptowall_docx_macro.yar \
                    yara-rules/phish_me/PM_Dyre_Delivery_:_dyre_cryptowall_crimeware.yar \
                    yara-rules/phish_me/PM_Dyre_Delivery_:_dyre_cryptowall_crimeware2.yar \
                    yara-rules/phish_me/PM_Dyre_Voice_Message.yar \
                    yara-rules/phish_me/PM_Zip_With_Exe.yar \
                    yara-rules/phish_me/PM_docx_with_vba_bin.yar \
                    yara-rules/phish_me/PM_outlook_setting_pdf_exe.yar \
                    yara-rules/phish_me/PPS_With_OLEObject.yar \
                    yara-rules/phish_me/PowerPoint_Embedded_OLE.yar \
                    yara-rules/phish_me/Zip_with_JS.yar \
                    yara-rules/phish_me/criakl_metadata.yar \
                    yara-rules/phish_me/cryptowall_phish.yar \
                    yara-rules/phish_me/mailers.yar \
                    yara-rules/phish_me/rar_with_JS.yar \
                    yara-rules/phish_me/rockloader.yar \
                    yara-rules/phish_me/viotto_keylogger.yar \
                    yara-rules/phoul/BLOWFISH_Constants.yar \
                    yara-rules/phoul/MD5_Constants.yar \
                    yara-rules/phoul/RC6_Constants.yar \
                    yara-rules/phoul/RIPEMD160_Constants.yar \
                    yara-rules/phoul/SHA1_Constants.yar \
                    yara-rules/phoul/SHA256_Constants.yar \
                    yara-rules/phoul/SHA512_Constants.yar \
                    yara-rules/phoul/WHIRLPOOL_Constants.yar \
                    yara-rules/plxsertr/ntserverdll.yar \
                    yara-rules/plxsertr/ntserverexe.yar \
                    yara-rules/proofpoint/AVIDVIPER_APT_BACKDOOR.yar \
                    yara-rules/proofpoint/AdGholas_mem.yar \
                    yara-rules/proofpoint/AdGholas_mem_MIME.yar \
                    yara-rules/proofpoint/AdGholas_mem_MIME_M2.yar \
                    yara-rules/proofpoint/AdGholas_mem_antisec.yar \
                    yara-rules/proofpoint/AdGholas_mem_antisec_M2.yar \
                    yara-rules/proofpoint/abaddon.yara \
                    yara-rules/proofpoint/blackmoon_banker.yar \
                    yara-rules/pveutin/magic_numbers.yar \
                    yara-rules/secureworks/Mirage_APT_Backdoor.yar \
                    yara-rules/secureworks/skeleton_key_injected_code.yar \
                    yara-rules/secureworks/skeleton_key_patcher.yar \
                    yara-rules/sentinelone/iOS.GuiInject.yara \
                    yara-rules/srozb/isfb.yar \
                    yara-rules/srozb/kronos.yar \
                    yara-rules/srozb/nymaim.yar \
                    yara-rules/swood/browser_pass.yar \
                    yara-rules/symantec/Bannerjack.yar \
                    yara-rules/symantec/Cadelle_1.yar \
                    yara-rules/symantec/Cadelle_2.yar \
                    yara-rules/symantec/Cadelle_3.yar \
                    yara-rules/symantec/Cadelle_4.yar \
                    yara-rules/symantec/Eventlog.yar \
                    yara-rules/symantec/Hacktool.yar \
                    yara-rules/symantec/Kwampirs.yar \
                    yara-rules/symantec/Multipurpose.yar \
                    yara-rules/symantec/Proxy.yar \
                    yara-rules/symantec/Securetunnel.yar \
                    yara-rules/symantec/comrat.yar \
                    yara-rules/symantec/fa.yar \
                    yara-rules/symantec/isPE.yar \
                    yara-rules/symantec/jiripbot___ascii___str___decrypt.yar \
                    yara-rules/symantec/jiripbot___unicode___str___decrypt.yar \
                    yara-rules/symantec/remsec_encrypted_api.yar \
                    yara-rules/symantec/remsec_executable_blob_32.yar \
                    yara-rules/symantec/remsec_executable_blob_64.yar \
                    yara-rules/symantec/remsec_executable_blob_parser.yar \
                    yara-rules/symantec/remsec_packer_A.yar \
                    yara-rules/symantec/remsec_packer_B.yar \
                    yara-rules/symantec/sav.yar \
                    yara-rules/symantec/turla___dropper.yar \
                    yara-rules/symantec/wipbot___2013___core.yar \
                    yara-rules/symantec/wipbot___2013___core___PDF.yar \
                    yara-rules/symantec/wipbot___2013___dll.yar \
                    yara-rules/tekdefense/DarkComet.yara \
                    yara-rules/venom23/Neurevt.yar \
                    yara-rules/vred/W32HavexNetscan.yar \
                    yara-rules/xanda/MS12_052.yar \
                    yara-rules/xanda/counterPHPredirectBHEK.yar \
                    yara-rules/xanda/iframeRedKit.yar \
                    yara-rules/xanda/jjEncode.yar \
                    yara-rules/xme/Worm_VBS_Uaper_B.yar \
                    yara-rules/xme/office_macro.yar \
                "

SCA_RAW_RESULT_FILE[yara] = "txt"

inherit sca-conv-to-export
inherit sca-datamodel
inherit sca-global
inherit sca-helper
inherit sca-license-filter
inherit sca-suppress

DEPENDS += "yara-rules-native yara-native"

def sca_yara_get_description(d, raw):
    items = {}
    for i in raw.split(","):
        h = i.split("=")
        if len(h) == 2:
            items[h[0]] = h[1].strip(" ").strip('"')

    needles = ["description", "Description", "desc", "comment", "Comment"]
    for n in needles:
        if n in items.keys():
            return items[n]
    return ""


def do_sca_conv_yara(d):
    import os
    import re

    package_name = d.getVar("PN")
    buildpath = d.getVar("SCA_SOURCES_DIR")

    pattern = r"^(?P<id>[a-zA-z_0-9]+)\s\[(?P<attr>.*?)\]\s(?P<file>.*)$"

    _suppress = sca_suppress_init(d, "SCA_UPC_EXTRA_SUPPRESS",
                                  d.expand("${STAGING_DATADIR_NATIVE}/yara-${SCA_MODE}-suppress"))
    _findings = []

    if os.path.exists(sca_raw_result_file(d, "yara")):
        with open(sca_raw_result_file(d, "yara"), "r") as f:
            for m in re.finditer(pattern, f.read(), re.MULTILINE):
                _desc = sca_yara_get_description(d, m.group("attr"))
                if not _desc:
                    continue
                try:
                    g = sca_get_model_class(d,
                                            PackageName=package_name,
                                            Tool="yara",
                                            BuildPath=buildpath,
                                            File=m.group("file"),
                                            Message=_desc,
                                            ID=m.group("id"),
                                            Severity="warning")
                    if _suppress.Suppressed(g):
                        continue
                    if g.Scope not in clean_split(d, "SCA_SCOPE_FILTER"):
                        continue
                    if g.Severity in sca_allowed_warning_level(d):
                        _findings.append(g)
                except Exception as exp:
                    bb.warn(str(exp))

    sca_add_model_class_list(d, _findings)
    return sca_save_model_to_string(d)

python do_sca_yara() {
    import os
    import subprocess

    cmd_output = ""
    _args = ["yara", "-r", "--no-warnings", "--print-meta"]
    _rules = [os.path.join(d.getVar("STAGING_DATADIR_NATIVE"), x) for x in clean_split(d, "SCA_YARA_MODULES")]
    for _r in _rules:
        try:
            cmd_output += subprocess.check_output(_args + [_r, d.getVar("IMAGE_ROOTFS")], universal_newlines=True, stderr=subprocess.STDOUT)
        except subprocess.CalledProcessError as e:
            cmd_output += e.stdout or ""

    with open(sca_raw_result_file(d, "yara"), "w") as o:
        o.write(cmd_output)

    ## Create data model
    d.setVar("SCA_DATAMODEL_STORAGE", "{}/yara.dm".format(d.getVar("T")))
    dm_output = do_sca_conv_yara(d)
    with open(d.getVar("SCA_DATAMODEL_STORAGE"), "w") as o:
        o.write(dm_output)

    sca_task_aftermath(d, "yara", get_fatal_entries(d, "SCA_UPC_EXTRA_FATAL",
                       d.expand("${STAGING_DATADIR_NATIVE}/yara-${SCA_MODE}-fatal")))
}

SCA_DEPLOY_TASK = "do_sca_deploy_yara_image"

python do_sca_deploy_yara_image() {
    sca_conv_deploy(d, "yara")
}

do_sca_yara[doc] = "Find suspious/malware vectors in image"
do_sca_deploy_yara_image[doc] = "Deploy results of do_sca_yara"
addtask do_sca_yara before do_image_complete after do_image
addtask do_sca_deploy_yara_image before do_image_complete after do_sca_yara

DEPENDS += "sca-image-yara-rules-native"
