SUMMARY = "The pluggable natural language linter for text and markdown."
DESCRIPTION = "The pluggable natural language linter for text and markdown."
HOMEPAGE = "https://github.com/textlint/textlint"

SRC_URI = "file://textlint.sca.description"

LICENSE = "MIT"
LIC_FILES_CHKSUM  = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

do_configure[noexec] = "1"

FILES_${PN} = "${datadir}/"

inherit native
inherit npm-helper

python do_compile() {
    import os
    import json

    # npm --prefix . install textlint@11.2.3
    # npm --prefix . install textlint-rule-no-todo@2.0.1
    # npm --prefix . install textlint-rule-no-start-duplicated-conjunction@2.0.2
    # npm --prefix . install textlint-rule-max-number-of-lines@1.0.3
    # npm --prefix . install textlint-rule-max-comma@1.0.4
    # npm --prefix . install textlint-rule-no-exclamation-question-mark@1.0.2
    # npm --prefix . install textlint-rule-ng-word@1.0.0
    # npm --prefix . install textlint-rule-no-dead-link@4.4.1
    # npm --prefix . install textlint-rule-no-empty-section@1.1.0
    # npm --prefix . install textlint-rule-unexpanded-acronym@1.2.3
    # npm --prefix . install textlint-rule-alex@1.3.1
    # npm --prefix . install textlint-rule-write-good@latest
    # npm --prefix . install textlint-rule-rousseau@1.4.5
    # npm --prefix . install textlint-rule-en-max-word-count@1.0.1
    # npm --prefix . install textlint-filter-rule-comments@1.2.2
    # npm --prefix . install textlint-plugin-html@0.2.0
    # npm --prefix . install textlint-plugin-rst@latest
    # npm --prefix . install textlint-rule-date-weekday-mismatch@1.0.5
    # npm --prefix . install textlint-rule-terminology@1.1.30
    # npm --prefix . install textlint-rule-period-in-list-item@0.3.0
    # npm --prefix . install textlint-rule-no-nfd@1.0.1
    # npm --prefix . install @textlint-rule/textlint-rule-no-invalid-control-character@1.2.0
    # npm --prefix . install textlint-rule-no-surrogate-pair@1.0.1
    # npm --prefix . install textlint-rule-abbr-within-parentheses@1.0.2
    # npm --prefix . install textlint-rule-common-misspellings@latest
    # npm --prefix . install textlint-rule-ginger@2.2.1
    # npm --prefix . install textlint-rule-apostrophe@1.0.0
    # npm --prefix . install textlint-rule-diacritics@0.0.2
    # npm --prefix . install textlint-rule-stop-words@1.0.12
    # npm --prefix . install textlint-rule-en-capitalization@2.0.1

    online_pkgs = ["textlint-rule-no-dead-link"]
    plugins = ["textlint-plugin-html", "textlint-plugin-rst"]
    filters = ["textlint-filter-rule-comments"]

    with open(os.path.join(d.getVar("B"), "online-rules.json"), "w") as o:
        json.dump(online_pkgs, o)

    ## Install needed pkgs
    pkgs = {
        "get-stream": "3.0.0",
        "lodash.intersection": "4.4.0",
        "unist-util-visit-parents": "2.0.1",
        "txt-ast-traverse": "1.2.1",
        "safe-regex": "1.1.0",
        "define-property": "2.0.2",
        "clone-regexp": "1.0.1",
        "is-regex": "1.0.4",
        "en-stemmer": "1.0.3",
        "fn-name": "2.0.1",
        "diff": "2.2.3",
        "pinkie-promise": "2.0.1",
        "spawn-to-readstream": "0.1.3",
        "textlint-rule-max-number-of-lines": "1.0.3",
        "text-table": "0.2.0",
        "oauth-sign": "0.9.0",
        "array-includes": "3.0.3",
        "get-stdin": "4.0.1",
        "bail": "1.0.3",
        "textlint-rule-helper": "1.2.0",
        "shellsubstitute": "1.2.0",
        "esprima": "4.0.1",
        "path-exists": "2.1.0",
        "unified-engine": "4.0.1",
        "is-alphabetical": "1.0.2",
        "nlcst-search": "1.5.0",
        "read-pkg-up": "1.0.1",
        "unherit": "1.1.1",
        "sentence-splitter": "2.3.2",
        "try-resolve": "1.0.1",
        "request": "2.88.0",
        "vfile-reporter": "4.0.0",
        "slice-ansi": "0.0.4",
        "select-section": "0.4.6",
        "encoding": "0.1.12",
        "pinkie": "2.0.4",
        "extend": "3.0.2",
        "lodash.assign": "3.2.0",
        "replace-ext": "1.0.0",
        "assert-plus": "1.0.0",
        "@textlint-rule/textlint-rule-no-invalid-control-character": "1.2.0",
        "process-nextick-args": "2.0.0",
        "create-error-class": "3.0.2",
        "find-up": "1.1.2",
        "lodash._bindcallback": "3.0.1",
        "bash-color": "0.0.3",
        "to-regex": "3.0.2",
        "capture-stack-trace": "1.0.1",
        "unist-util-select": "1.5.0",
        "wordwrap": "1.0.0",
        "is-installed-globally": "0.1.0",
        "timed-out": "4.0.1",
        "misspellings": "1.1.0",
        "crypt": "0.0.2",
        "es-to-primitive": "1.2.0",
        "limit-spawn": "0.0.3",
        "parse-entities": "1.2.1",
        "asn1": "0.2.4",
        "nlcst-to-string": "2.0.2",
        "quotation": "1.1.1",
        "textlint-rule-write-good": "1.6.2",
        "path-key": "2.0.1",
        "assign-symbols": "1.0.0",
        "resolve-from": "4.0.0",
        "nlcst-is-literal": "1.1.2",
        "textlint-rule-unexpanded-acronym": "1.2.3",
        "path-is-inside": "1.0.2",
        "textlint-rule-no-nfd": "1.0.1",
        "glob": "7.1.3",
        "p-try": "1.0.0",
        "sshpk": "1.16.1",
        "spdx-correct": "3.1.0",
        "strip-ansi": "4.0.0",
        "textlint-plugin-rst": "0.1.1",
        "npm-run-path": "2.0.2",
        "hosted-git-info": "2.7.1",
        "unified-diff": "1.0.2",
        "match-casing": "1.0.1",
        "humannames": "1.0.5",
        "from": "0.1.7",
        "safe-buffer": "5.1.2",
        "read-pkg": "1.1.0",
        "trim-trailing-lines": "1.1.1",
        "regex-not": "1.0.2",
        "crypto-random-string": "1.0.0",
        "passive-voice": "0.1.0",
        "number-is-nan": "1.0.1",
        "universalify": "0.1.2",
        "textlint-rule-en-capitalization": "2.0.1",
        "is-hexadecimal": "1.0.2",
        "has-flag": "3.0.0",
        "minimist": "1.2.0",
        "is-path-inside": "1.0.1",
        "ent": "2.2.0",
        "stream-combiner": "0.0.4",
        "repeat-string": "1.6.1",
        "uuid": "3.3.2",
        "once": "1.4.0",
        "vfile-message": "1.1.1",
        "check-ends-with-period": "1.0.1",
        "tweetnacl": "0.14.5",
        "mime-types": "2.1.24",
        "har-validator": "5.1.3",
        "remark-parse": "4.0.0",
        "http-signature": "1.2.0",
        "lowercase-keys": "1.0.1",
        "lodash.defaults": "3.1.2",
        "circular-json": "0.3.3",
        "lodash.keys": "3.1.2",
        "define-properties": "1.1.3",
        "fs-extra": "5.0.0",
        "sprintf-js": "1.0.3",
        "lodash._baseassign": "3.2.0",
        "jsprim": "1.4.1",
        "core-util-is": "1.0.2",
        "combined-stream": "1.0.7",
        "param-case": "1.1.2",
        "has-symbols": "1.0.0",
        "too-wordy": "0.1.6",
        "graceful-fs": "4.1.15",
        "weasel-words": "0.1.1",
        "path-is-absolute": "1.0.1",
        "textlint-rule-no-start-duplicated-conjunction": "2.0.2",
        "vfile-statistics": "1.1.2",
        "entities": "1.1.2",
        "is-finite": "1.0.2",
        "split": "0.2.10",
        "remark-message-control": "4.1.1",
        "lodash._isiterateecall": "3.0.9",
        "map-obj": "1.0.1",
        "textlint-rule-en-max-word-count": "1.0.1",
        "textlint-rule-ginger": "2.2.1",
        "isexe": "2.0.0",
        "jsonfile": "4.0.0",
        "ret": "0.1.15",
        "nlcst-normalize": "2.1.2",
        "textlint-rule-ng-word": "1.0.0",
        "ansi-align": "2.0.0",
        "rc": "1.2.8",
        "repeating": "2.0.1",
        "got": "6.7.1",
        "x-is-string": "0.1.0",
        "@textlint/kernel": "3.1.4",
        "kind-of": "6.0.2",
        "map-like": "1.1.3",
        "split-string-words": "1.0.0",
        "isomorphic-fetch": "2.2.1",
        "unist-util-visit": "1.4.0",
        "aws4": "1.8.0",
        "match-index": "1.0.1",
        "psl": "1.1.31",
        "end-of-stream": "1.4.1",
        "remark-frontmatter": "1.3.1",
        "write": "0.2.1",
        "textlint-rule-common-misspellings": "1.0.1",
        "unist-util-stringify-position": "1.1.2",
        "parse-english": "4.1.1",
        "supports-color": "4.5.0",
        "textlint-rule-no-dead-link": "4.4.1",
        "deep-equal": "1.0.1",
        "gingerbread": "0.5.0",
        "is-date-object": "1.0.1",
        "trim": "0.0.1",
        "pump": "1.0.3",
        "pluralize": "7.0.0",
        "unzip-response": "2.0.1",
        "@textlint/text-to-ast": "3.1.2",
        "latest-version": "3.1.0",
        "is-plain-object": "2.0.4",
        "textlint-filter-rule-comments": "1.2.2",
        "brace-expansion": "1.1.11",
        "es-abstract": "1.13.0",
        "camelcase-keys": "2.1.0",
        "js-yaml": "3.13.1",
        "map-stream": "0.1.0",
        "global-dirs": "0.1.1",
        "validate-npm-package-license": "3.0.4",
        "rousseau": "1.0.5",
        "mkdirp": "0.5.1",
        "lodash.sortby": "4.7.0",
        "chrono-node": "1.3.11",
        "currently-unhandled": "0.4.1",
        "textlint-rule-max-comma": "1.0.4",
        "prepend-http": "1.0.4",
        "escape-string-regexp": "1.0.5",
        "table": "3.8.3",
        "parse-json": "4.0.0",
        "camelcase": "1.2.1",
        "en-inflectors": "1.0.12",
        "unist-util-filter": "0.2.1",
        "is-empty": "1.2.0",
        "inherits": "2.0.3",
        "xdg-basedir": "3.0.0",
        "unist-util-is": "1.0.0",
        "alex": "5.1.0",
        "unist-util-visit-children": "1.1.2",
        "error-ex": "1.3.2",
        "is-data-descriptor": "1.0.0",
        "execa": "0.7.0",
        "object-keys": "0.4.0",
        "levn": "0.3.0",
        "collapse-white-space": "1.0.4",
        "unique-string": "1.0.0",
        "strip-eof": "1.0.0",
        "bcrypt-pbkdf": "1.0.2",
        "is-decimal": "1.0.2",
        "typedarray": "0.0.6",
        "lodash": "3.10.1",
        "textlint-rule-alex": "1.3.1",
        "is-npm": "1.0.0",
        "split-transform-stream": "0.1.1",
        "ignore": "3.3.10",
        "mdast-comment-marker": "1.1.0",
        "crc": "3.2.1",
        "format": "0.2.2",
        "array-find-index": "1.0.2",
        "jsonify": "0.0.0",
        "normalize-package-data": "2.5.0",
        "textlint-rule-no-empty-section": "1.1.0",
        "uri-js": "4.2.2",
        "ini": "1.3.5",
        "spdx-license-ids": "3.0.4",
        "has-ansi": "2.0.0",
        "write-good": "0.11.3",
        "split-lines": "2.0.0",
        "import-lazy": "2.1.0",
        "string_decoder": "0.10.31",
        "unorm": "1.5.0",
        "redent": "1.0.0",
        "fast-levenshtein": "2.0.6",
        "loud-rejection": "1.6.0",
        "@textlint/textlint-plugin-text": "4.1.4",
        "moment": "2.24.0",
        "concat-stream": "1.6.2",
        "es6-promisify": "5.0.0",
        "vfile-sort": "2.2.0",
        "widest-line": "2.0.1",
        "retext-profanities": "4.4.0",
        "array-iterate": "1.1.2",
        "pump-chain": "1.0.0",
        "duplexer": "0.1.1",
        "sentence-case": "1.1.3",
        "markdown-escapes": "1.0.2",
        "domelementtype": "1.3.1",
        "unist-util-remove-position": "1.1.2",
        "lru-cache": "4.1.5",
        "performance-now": "2.1.0",
        "mime-db": "1.40.0",
        "iconv-lite": "0.4.24",
        "registry-url": "3.1.0",
        "@textlint/fixer-formatter": "3.1.3",
        "lower-case": "1.1.4",
        "state-toggle": "1.0.1",
        "ajv": "6.10.0",
        "character-reference-invalid": "1.1.2",
        "@azu/format-text": "1.0.1",
        "meow": "3.7.0",
        "os-homedir": "1.0.2",
        "structured-source": "3.0.2",
        "textlint": "11.2.3",
        "md5": "2.2.1",
        "textlint-util-to-string": "2.1.1",
        "through2": "2.0.5",
        "boundary": "1.0.1",
        "vfile-location": "2.0.4",
        "concat-map": "0.0.1",
        "is-buffer": "1.1.6",
        "is-file": "1.0.0",
        "function-bind": "1.1.1",
        "@types/bluebird": "3.5.26",
        "tough-cookie": "2.4.3",
        "character-entities": "1.2.2",
        "require-from-string": "2.0.2",
        "json-stringify-safe": "5.0.1",
        "util-deprecate": "1.0.2",
        "trough": "1.0.3",
        "fs.realpath": "1.0.0",
        "git-diff-tree": "1.0.0",
        "pseudomap": "1.0.2",
        "unified-message-control": "1.0.4",
        "find-line-column": "0.5.2",
        "textlint-rule-no-surrogate-pair": "1.0.1",
        "tokenize-htmltext": "1.0.0",
        "mdast-util-to-nlcst": "3.2.2",
        "verror": "1.10.0",
        "cross-spawn": "5.1.0",
        "@textlint/textlint-plugin-markdown": "5.1.4",
        "bluebird": "3.5.4",
        "no-cliches": "0.1.1",
        "url-parse-lax": "1.0.0",
        "get-url-origin": "1.0.1",
        "textlint-rule-rousseau": "1.4.5",
        "lodash.uniq": "4.5.0",
        "is-whitespace-character": "1.0.2",
        "getpass": "0.1.7",
        "tokenize-text": "1.1.3",
        "textlint-rule-no-todo": "2.0.1",
        "is-plain-obj": "1.1.0",
        "has": "1.0.3",
        "file-entry-cache": "2.0.0",
        "signal-exit": "3.0.2",
        "package-json": "4.0.1",
        "ansi-styles": "3.2.1",
        "minimatch": "3.0.4",
        "bubble-stream-error": "0.0.1",
        "en-lexicon": "1.0.11",
        "lodash.restparam": "3.6.1",
        "safer-buffer": "2.1.2",
        "strip-indent": "1.0.1",
        "punycode": "1.4.1",
        "is-arrayish": "0.2.1",
        "is-retry-allowed": "1.1.0",
        "color-convert": "1.9.3",
        "retext-english": "3.0.2",
        "term-size": "1.2.0",
        "textlint-rule-period-in-list-item": "0.3.0",
        "readable-stream": "3.3.0",
        "regexp.prototype.flags": "1.2.0",
        "is-descriptor": "1.0.2",
        "lodash.uniqwith": "4.5.0",
        "isobject": "3.0.1",
        "flat-cache": "1.3.4",
        "configstore": "3.1.2",
        "chalk": "2.4.2",
        "textlint-rule-date-weekday-mismatch": "1.0.5",
        "boolbase": "1.0.0",
        "fast-deep-equal": "2.0.1",
        "retext-equality": "3.2.0",
        "aws-sign2": "0.7.0",
        "@textlint/linter-formatter": "3.1.3",
        "strip-json-comments": "2.0.1",
        "is-typedarray": "1.0.0",
        "nth-check": "1.0.2",
        "attach-ware": "1.1.1",
        "argparse": "1.0.10",
        "es6-promise": "4.2.6",
        "is-stream": "1.1.0",
        "escape-html": "1.0.3",
        "semver": "5.7.0",
        "cli-table": "0.3.1",
        "event-stream": "3.1.7",
        "@textlint/regexp-string-matcher": "1.0.2",
        "is-utf8": "0.2.1",
        "unist-util-modify-children": "1.1.3",
        "deep-is": "0.1.3",
        "remark-retext": "3.1.2",
        "is-symbol": "1.0.2",
        "is-ci": "1.2.1",
        "interop-require": "1.0.0",
        "hast": "0.0.2",
        "ansi-regex": "3.0.0",
        "tunnel-agent": "0.6.0",
        "rimraf": "2.6.3",
        "textlint-rule-abbr-within-parentheses": "1.0.2",
        "registry-auth-token": "3.4.0",
        "lodash.difference": "4.5.0",
        "textlint-rule-no-exclamation-question-mark": "1.0.2",
        "imurmurhash": "0.1.4",
        "textlint-rule-diacritics": "0.0.2",
        "is-regexp": "1.0.0",
        "unified": "2.1.4",
        "domhandler": "2.4.2",
        "strip-bom": "2.0.0",
        "caseless": "0.12.0",
        "dashdash": "1.14.1",
        "buffer-from": "1.1.1",
        "boxen": "1.3.0",
        "to-vfile": "2.2.0",
        "code-point-at": "1.1.0",
        "@textlint/feature-flag": "3.1.2",
        "dom-serializer": "0.1.1",
        "textlint-rule-terminology": "1.1.30",
        "har-schema": "2.0.0",
        "p-finally": "1.0.0",
        "shebang-command": "1.2.0",
        "execall": "1.0.0",
        "make-dir": "1.3.0",
        "p-limit": "1.3.0",
        "unist-util-map": "1.0.4",
        "which": "1.3.1",
        "resolve": "1.10.1",
        "character-entities-legacy": "1.1.2",
        "through": "2.3.8",
        "optionator": "0.8.2",
        "charenc": "0.0.2",
        "object.assign": "4.1.0",
        "delayed-stream": "1.0.0",
        "@textlint/types": "1.1.3",
        "cities-list": "1.0.3",
        "@textlint/markdown-to-ast": "6.1.2",
        "xtend": "2.1.2",
        "json-stable-stringify": "1.0.1",
        "write-file-atomic": "2.4.2",
        "is-word-character": "1.0.2",
        "textlint-rule-stop-words": "1.0.12",
        "untildify": "2.1.0",
        "wrap-fn": "0.1.5",
        "ajv-keywords": "1.5.1",
        "prelude-ls": "1.1.2",
        "dot-prop": "4.2.0",
        "is-redirect": "1.0.0",
        "x-is-function": "1.0.4",
        "rc-config-loader": "2.0.2",
        "npm-prefix": "1.2.0",
        "cli-boxes": "1.0.0",
        "lodash.isarray": "3.0.4",
        "type-check": "0.3.2",
        "commander": "2.20.0",
        "domutils": "1.7.0",
        "wrappy": "1.0.2",
        "emoji-regex": "6.5.1",
        "decamelize": "1.2.0",
        "path-parse": "1.0.6",
        "@textlint/ast-node-types": "4.2.1",
        "xml-escape": "1.1.0",
        "balanced-match": "1.0.0",
        "unique-concat": "0.2.2",
        "color-name": "1.1.3",
        "vfile-find-up": "2.0.2",
        "co": "3.1.0",
        "form-data": "2.3.3",
        "extend-shallow": "3.0.2",
        "json-schema": "0.2.3",
        "string-width": "2.1.1",
        "extsprintf": "1.3.0",
        "en-pos": "1.0.16",
        "lodash.isarguments": "3.1.0",
        "pify": "3.0.0",
        "fault": "1.0.2",
        "load-plugin": "2.3.0",
        "is-alphanumerical": "1.0.2",
        "is-callable": "1.1.4",
        "forever-agent": "0.6.1",
        "textlint-rule-apostrophe": "1.0.0",
        "p-locate": "2.0.0",
        "fast-json-stable-stringify": "2.0.0",
        "end-with": "1.0.2",
        "asynckit": "0.4.0",
        "json-schema-traverse": "0.4.1",
        "shebang-regex": "1.0.0",
        "array.prototype.find": "2.0.4",
        "locate-path": "2.0.0",
        "indent-string": "2.1.0",
        "lodash._createassigner": "3.1.1",
        "e-prime": "0.10.2",
        "adverb-where": "0.0.9",
        "json5": "1.0.1",
        "isarray": "0.0.1",
        "spdx-expression-parse": "3.0.0",
        "vfile": "1.4.0",
        "@textlint/ast-traverse": "2.1.2",
        "semver-diff": "2.1.0",
        "whatwg-fetch": "3.0.0",
        "is-supported-regexp-flag": "1.0.1",
        "log-symbols": "1.0.2",
        "path-to-glob-pattern": "1.0.2",
        "property-information": "2.0.0",
        "lodash._basecopy": "3.0.1",
        "simple-lru-cache": "0.0.1",
        "cuss": "1.13.1",
        "htmlparser2": "3.10.1",
        "string.prototype.padstart": "3.0.0",
        "object-assign": "4.1.1",
        "duplexer3": "0.1.4",
        "parse-latin": "4.1.1",
        "traverse": "0.6.6",
        "git-spawned-stream": "0.1.1",
        "ware": "1.3.0",
        "json-parse-better-errors": "1.0.2",
        "jsbn": "0.1.1",
        "ms": "2.0.0",
        "is-obj": "1.0.1",
        "trim-newlines": "1.0.0",
        "ecc-jsbn": "0.1.2",
        "node-fetch": "1.7.3",
        "update-notifier": "2.5.0",
        "spdx-exceptions": "2.2.0",
        "load-json-file": "4.0.0",
        "path-type": "3.0.0",
        "pause-stream": "0.0.11",
        "debug": "2.6.9",
        "lodash._getnative": "3.9.1",
        "object.values": "1.1.0",
        "css-selector-parser": "1.3.0",
        "tokenize-english": "1.0.3",
        "deep-extend": "0.6.0",
        "isstream": "0.1.2",
        "is-hidden": "1.1.1",
        "ci-info": "1.6.0",
        "sliced": "1.0.1",
        "colors": "1.0.3",
        "textlint-plugin-html": "0.2.0",
        "qs": "6.5.2",
        "inflight": "1.0.6",
        "is-fullwidth-code-point": "2.0.0",
        "is-accessor-descriptor": "1.0.0",
        "is-object": "1.0.1",
        "@azu/style-format": "1.0.0",
        "is-capitalized": "1.0.0",
        "flatmap": "0.0.3",
        "unist-util-position": "3.0.2",
        "is-extendable": "1.0.1",
        "yallist": "2.1.2"
    }

    for name, version in pkgs.items():
        npm_install_package(d, d.getVar("B"), name, version)

    ## Strip of hardcoded paths in packages
    npm_postinst_fix_paths(d, d.getVar("B"), "textlint")
}

INSANE_SKIP_${PN} += "host-user-contaminated"

do_install() {
    mkdir -p ${D}${datadir}/textlint/
    cp -Ra ${B}/* ${D}${datadir}/textlint
    install ${WORKDIR}/textlint.sca.description ${D}${datadir}
}

