SUMMARY = "Native variant of standard"
DESCRIPTION = "Native build of standard."

SRC_URI = "file://standard.sca.description \
           file://standard.sca.score"

LICENSE = "MIT"
LIC_FILES_CHKSUM  = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

do_configure[noexec] = "1"

FILES_${PN} = "${datadir}/"

inherit native
inherit npm-helper

python do_compile() {
    # npm --prefix . install standard@12.0.1

    ## Install needed pkgs
    pkgs = {
        "which": "1.3.1",
        "esutils": "2.0.2",
        "loose-envify": "1.4.0",
        "array-includes": "3.0.3",
        "rxjs": "5.5.12",
        "esquery": "1.0.1",
        "eslint": "5.4.0",
        "cli-cursor": "2.1.0",
        "strip-ansi": "4.0.0",
        "os-tmpdir": "1.0.2",
        "text-table": "0.2.0",
        "type-check": "0.3.2",
        "pkg-dir": "2.0.0",
        "is-regex": "1.0.4",
        "glob": "7.1.3",
        "path-parse": "1.0.6",
        "validate-npm-package-license": "3.0.4",
        "ansi-styles": "3.2.1",
        "color-convert": "1.9.3",
        "debug-log": "1.0.1",
        "load-json-file": "4.0.0",
        "mkdirp": "0.5.1",
        "ajv-keywords": "3.4.0",
        "string-width": "2.1.1",
        "xtend": "4.0.1",
        "strip-json-comments": "2.0.1",
        "onetime": "2.0.1",
        "read-pkg-up": "2.0.0",
        "eslint-utils": "1.3.1",
        "wrappy": "1.0.2",
        "require-uncached": "1.0.3",
        "spdx-exceptions": "2.2.0",
        "path-exists": "3.0.0",
        "semver": "5.7.0",
        "progress": "2.0.3",
        "functional-red-black-tree": "1.0.1",
        "balanced-match": "1.0.0",
        "is-date-object": "1.0.1",
        "slice-ansi": "1.0.0",
        "eslint-plugin-react": "7.11.1",
        "cross-spawn": "6.0.5",
        "eslint-config-standard": "12.0.0",
        "standard": "12.0.1",
        "has": "1.0.3",
        "p-locate": "2.0.0",
        "acorn": "6.1.1",
        "write": "0.2.1",
        "path-is-absolute": "1.0.1",
        "argparse": "1.0.10",
        "ansi-escapes": "3.2.0",
        "esrecurse": "4.2.1",
        "deglob": "2.1.1",
        "optionator": "0.8.2",
        "ansi-regex": "3.0.0",
        "prelude-ls": "1.1.2",
        "eslint-scope": "4.0.3",
        "once": "1.4.0",
        "json-parse-better-errors": "1.0.2",
        "through": "2.3.8",
        "path-key": "2.0.1",
        "isarray": "1.0.0",
        "resolve": "1.10.1",
        "eslint-import-resolver-node": "0.3.2",
        "es-to-primitive": "1.2.0",
        "deep-is": "0.1.3",
        "js-tokens": "3.0.2",
        "inflight": "1.0.6",
        "get-stdin": "6.0.0",
        "normalize-package-data": "2.5.0",
        "standard-engine": "9.0.0",
        "graceful-fs": "4.1.15",
        "define-properties": "1.1.3",
        "symbol-observable": "1.0.1",
        "ignore": "4.0.6",
        "doctrine": "1.5.0",
        "imurmurhash": "0.1.4",
        "nice-try": "1.0.5",
        "chardet": "0.4.2",
        "contains-path": "0.1.0",
        "pluralize": "7.0.0",
        "color-name": "1.1.3",
        "es-abstract": "1.13.0",
        "object-assign": "4.1.1",
        "has-flag": "3.0.0",
        "file-entry-cache": "2.0.0",
        "find-up": "2.1.0",
        "spdx-license-ids": "3.0.4",
        "sprintf-js": "1.0.3",
        "is-resolvable": "1.1.0",
        "shebang-command": "1.2.0",
        "json-stable-stringify-without-jsonify": "1.0.1",
        "pkg-conf": "2.1.0",
        "pkg-config": "1.1.1",
        "is-arrayish": "0.2.1",
        "flat-cache": "1.3.4",
        "read-pkg": "2.0.0",
        "ajv": "6.10.0",
        "estraverse": "4.2.0",
        "wordwrap": "1.0.0",
        "p-try": "1.0.0",
        "mimic-fn": "1.2.0",
        "safer-buffer": "2.1.2",
        "callsites": "0.2.0",
        "brace-expansion": "1.1.11",
        "escape-string-regexp": "1.0.5",
        "eslint-visitor-keys": "1.0.0",
        "external-editor": "2.2.0",
        "espree": "4.1.0",
        "mute-stream": "0.0.7",
        "eslint-module-utils": "2.4.0",
        "has-symbols": "1.0.0",
        "uri-js": "4.2.2",
        "eslint-plugin-import": "2.14.0",
        "chalk": "2.4.2",
        "strip-bom": "3.0.0",
        "supports-color": "2.0.0",
        "run-parallel": "1.1.9",
        "iconv-lite": "0.4.24",
        "regexpp": "2.0.1",
        "eslint-plugin-node": "7.0.1",
        "figures": "2.0.0",
        "globals": "11.11.0",
        "levn": "0.3.0",
        "inquirer": "5.2.0",
        "is-symbol": "1.0.2",
        "object-keys": "1.1.1",
        "fast-levenshtein": "2.0.6",
        "fast-json-stable-stringify": "2.0.0",
        "isexe": "2.0.0",
        "fast-deep-equal": "2.0.1",
        "run-async": "2.3.0",
        "p-limit": "1.3.0",
        "lodash": "4.17.11",
        "uniq": "1.0.1",
        "inherits": "2.0.3",
        "minimist": "1.2.0",
        "jsx-ast-utils": "2.1.0",
        "is-promise": "2.1.0",
        "eslint-plugin-promise": "4.0.1",
        "signal-exit": "3.0.2",
        "fs.realpath": "1.0.0",
        "tmp": "0.0.33",
        "cli-width": "2.2.0",
        "json-schema-traverse": "0.4.1",
        "rimraf": "2.6.3",
        "debug": "2.6.9",
        "pify": "3.0.0",
        "circular-json": "0.3.3",
        "find-root": "1.1.0",
        "parse-json": "4.0.0",
        "function-bind": "1.1.1",
        "acorn-jsx": "5.0.1",
        "shebang-regex": "1.0.0",
        "error-ex": "1.3.2",
        "minimatch": "3.0.4",
        "js-yaml": "3.13.1",
        "esprima": "4.0.1",
        "caller-path": "0.1.0",
        "is-callable": "1.1.4",
        "ms": "2.1.1",
        "natural-compare": "1.4.0",
        "hosted-git-info": "2.7.1",
        "eslint-plugin-standard": "4.0.0",
        "spdx-correct": "3.1.0",
        "babel-code-frame": "6.26.0",
        "restore-cursor": "2.0.0",
        "punycode": "2.1.1",
        "spdx-expression-parse": "3.0.0",
        "locate-path": "2.0.0",
        "has-ansi": "2.0.0",
        "eslint-plugin-es": "1.4.0",
        "concat-map": "0.0.1",
        "prop-types": "15.7.2",
        "path-is-inside": "1.0.2",
        "table": "4.0.3",
        "path-type": "2.0.0",
        "eslint-config-standard-jsx": "6.0.2",
        "is-fullwidth-code-point": "2.0.0",
        "react-is": "16.8.6",
        "resolve-from": "1.0.1"
    }

    for name, version in pkgs.items():
        npm_install_package(d, d.getVar("B"), name, version)

    ## Strip of hardcoded paths in packages
    npm_postinst_fix_paths(d, d.getVar("B"), "standard")
}

INSANE_SKIP_${PN} += "host-user-contaminated"

do_install() {
    mkdir -p ${D}${datadir}/standard
    cp -Ra ${B}/* ${D}${datadir}/standard
    install ${WORKDIR}/standard.sca.description ${D}${datadir}
    install ${WORKDIR}/standard.sca.score ${D}${datadir}
}

