# Distro Layer configuration
# DO NOT USE THIS DISTRO FOR SOMETHING PRODUCTIVE
# THIS IS JUST MEANT FOR TESTING
include conf/distro/poky.conf
DISTRO = "scatest"
DISTRO_NAME = "SCA Test distribution"
DISTRO_VERSION = "1.0"
SDK_VENDOR = "-scatestsdk"
SDK_VERSION = "${DISTRO_VERSION}"
MAINTAINER = "kweihmann@outlook.com"

TARGET_VENDOR = "-scatest"

# Override these in poky based distros
DISTRO_EXTRA_RDEPENDS += "packagegroup-core-boot"
DISTRO_EXTRA_RRECOMMENDS += ""

# Remove all audio and graphics related distro backfills
# we do not need them for our purposes
DISTRO_FEATURES_OPTED_OUT:append = " opengl ptest wayland vulkan pulseaudio sysvinit"
DISTRO_FEATURES:append = " systemd usrmerge ext2"

INIT_MANAGER = "systemd"

PACKAGE_CLASSES = "package_ipk"

# SCA specific settings
INHERIT += "rm_work"

# Disable the creation of cache files for 
# python native packages to address this issues
# described at
# https://github.com/priv-kweihmann/meta-sca/issues/1077
# https://github.com/priv-kweihmann/meta-sca/issues/1086
INHERIT += "no-native-pycache"

# Disable SPDX
INHERIT += "no-spdx"

BB_HASHSERVE_DB_DIR = "${SSTATE_DIR}"
