#! /bin/sh
# This script should check all non-github/pypi packages
# If there are updates available

PKGS="\
        checkbashism-native \
        libtalloc-native \
        perl-b-keywords-native \
        perl-class-data-inheritable-native \
        perl-class-inspector-native \
        perl-class-tiny-native \
        perl-clone-native \
        perl-config-tiny-native \
        perl-devel-stacktrace-native \
        perl-en-lingua-inflect-native \
        perl-exception-class-native \
        perl-exporter-tiny-native \
        perl-extutils-config-native \
        perl-extutils-helper-native \
        perl-extutils-installpaths-native \
        perl-file-sharedir-install-native \
        perl-file-sharedir-native \
        perl-file-spec-native \
        perl-file-which-native \
        perl-io-string-native \
        perl-list-moreutils-native \
        perl-list-utils-native \
        perl-module-build-tiny-native \
        perl-module-pluggable-native \
        perl-params-util-native \
        perl-path-tiny-native \
        perl-perl-tidy-native \
        perl-pod-shell-native \
        perl-ppi-native \
        perl-ppix-quotelike-native \
        perl-ppix-regexp-native \
        perl-ppix-utilities-native \
        perl-readonly-native \
        perl-string-format-native \
        perl-task-weaken-native \
        perl-term-ansicolor-native \
        perl-test-deep-native \
        perl-text-parsewords-native \
        python3-anytree-native \
        python3-appdirs-native \
        python3-asn1crypto-native \
        python3-astor-native \
        python3-astroids-native \
        python3-atomicwrites-native \
        python3-attrs-native \
        python3-babel-native \
        python3-bandit-native \
        python3-bashate-native \
        python3-bcrypt-native \
        python3-black-native \
        python3-cached-property-native \
        python3-capstone-native \
        python3-certifi-native \
        python3-cffi-native \
        python3-chardet-native \
        python3-click-native \
        python3-cohesion-native \
        python3-colorama-native \
        python3-configargparse-native \
        python3-coverage-native \
        python3-cryptography-native \
        python3-darglint-native \
        python3-ddt-native \
        python3-decorator-native \
        python3-dennis-native \
        python3-detect-secrets-native \
        python3-docutils-native \
        python3-dparse-native \
        python3-entrypoints-native \
        python3-enum-compat-native \
        python3-eradicate-native \
        python3-flake8-2020-native \
        python3-flake8-annotations-complexity-native \
        python3-flake8-bandit-native \
        python3-flake8-broken-line-native \
        python3-flake8-bugbear-native \
        python3-flake8-builtins-native \
        python3-flake8-coding-native \
        python3-flake8-commas-native \
        python3-flake8-comprehensions-native \
        python3-flake8-debugger-native \
        python3-flake8-dlint-native \
        python3-flake8-docstrings-native \
        python3-flake8-eradicate-native \
        python3-flake8-executable-native \
        python3-flake8-fixme-native \
        python3-flake8-import-order-native \
        python3-flake8-isort-native \
        python3-flake8-logging-format-native \
        python3-flake8-mutable-native \
        python3-flake8-native \
        python3-flake8-pep3101-native \
        python3-flake8-polyfill-native \
        python3-flake8-print-native \
        python3-flake8-quotes-native \
        python3-flake8-rst-docstrings-native \
        python3-flake8-sca-native \
        python3-flake8-strict-native \
        python3-flake8-string-format-native \
        python3-flake8-variables-names-native \
        python3-flawfinder-native \
        python3-future-native \
        python3-gitdb-native \
        python3-gitpython-native \
        python3-gixy-native \
        python3-idna-native \
        python3-importlab-native \
        python3-importlib-metadata-native \
        python3-isort-native \
        python3-jinja2-native \
        python3-jsonmerge-native \
        python3-looong-native \
        python3-markupsafe-native \
        python3-mccabe-native \
        python3-more-itertools-native \
        python3-msgcheck-native \
        python3-mypy-extensions-native \
        python3-mypy-native \
        python3-networkx-native \
        python3-ninja-native \
        python3-nose-native \
        python3-packaging-native \
        python3-paramiko-native \
        python3-pathlib2-native \
        python3-pathspec-native \
        python3-pbr-native \
        python3-pep8-naming-native \
        python3-pep8-native \
        python3-pluggy-native \
        python3-polib-native \
        python3-proselint-native \
        python3-py-native \
        python3-pyasn1-native \
        python3-pycodestyle-native \
        python3-pycparser-native \
        python3-pydocstyle-native \
        python3-pyelftools-native \
        python3-pyenchant-native \
        python3-pyfindinjection-native \
        python3-pyflakes-native \
        python3-pygments-native \
        python3-pylama-native \
        python3-pylazy-object-proxy-native \
        python3-pylint-native \
        python3-pynacl-native \
        python3-pyparsing-native \
        python3-pysymbolcheck-native \
        python3-pytest-native \
        python3-pytest-runner-native \
        python3-python-magic-native \
        python3-pytype-native \
        python3-pytz-native \
        python3-pyyaml-native \
        python3-requests-native \
        python3-restructuredtext-lint-native \
        python3-ropgadget-native \
        python3-ruamelyaml-native \
        python3-safety-native \
        python3-scandir-native \
        python3-scikit-build-native \
        python3-setuptools-lint-native \
        python3-setuptools-native \
        python3-setuptools-scm-git-archive-native \
        python3-setuptools-scm-native \
        python3-six-native \
        python3-snowballstemmer-native \
        python3-stevedore-native \
        python3-systemdunitparser-native \
        python3-testfixtures-native \
        python3-toml-native \
        python3-typed-ast-native \
        python3-typing-extensions-native \
        python3-urllib3-native \
        python3-vulture-native \
        python3-wcwidth-native \
        python3-wemake-python-styleguide-native \
        python3-wheel-native \
        python3-wrapt-native \
        python3-yamllint-native \
        python3-zipp-native \
        shellcheck-native \
        sparse-native \
        tiger-native \
      "

for p in ${PKGS}; do
    echo "Check ${p}..."
    devtool check-upgrade-status ${p} 2>&1 | grep "INFO:"
done
