#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2024, Konrad Weihmann

import argparse
import os
import re
import sys
from urllib.parse import urlparse

import tomli
from oelint_parser.cls_item import FlagAssignment, Variable
from oelint_parser.cls_stash import Stash


def create_parser():
    parser = argparse.ArgumentParser(
        description='Crates list updater')
    parser.add_argument("--faillog", default=None, help="Path to failure log")
    parser.add_argument("sources", help="path to the sources dir")
    parser.add_argument("recipe", help="name of the python package")
    return parser.parse_args()


def parse_crates(filepath, self_provided: list):
    res = set()
    checksums = {}
    git_source_format = ''
    with open(filepath, 'rb') as i:
        cnt = tomli.load(i)
        for item in cnt.get('package', []):
            name = item.get('name', '')
            version = item.get('version', '')
            checksum = item.get('checksum')
            source = item.get('source', '')
            if not version or not name:
                continue
            if name in self_provided or version in ['0.0.0']:
                continue
            parsed = urlparse(source)
            if 'git' in parsed.scheme:
                resname = parsed.path.replace("/", "-")
                res.add(
                    f'git://{parsed.hostname}{parsed.path};protocol=https;rev={parsed.fragment};nobranch=1;destsuffix=cargo_home/bitbake/{name}-{version}')
                if resname not in git_source_format:
                    git_source_format += f'-{resname}'
            else:
                res.add(f'crate://crates.io/{name}/{version}')
                checksums[f'{name}-{version}'] = checksum
    return (sorted(res), checksums, git_source_format)


def get_crates(args):
    res = []
    checksums = {}
    self_provided = set()
    for root, dirs, _ in os.walk(args.sources):
        for dir in dirs:
            fullpath = os.path.join(root, dir)
            parent = os.path.basename(os.path.dirname(fullpath))
            if parent in ['crates']:
                self_provided.add(os.path.basename(fullpath))
    for root, _, files in os.walk(args.sources):
        for file in files:
            fullpath = os.path.join(root, file)
            if file in ['Cargo.lock'] and '/crates/' not in fullpath:
                res, checksums, git_source_format = parse_crates(
                    fullpath, self_provided)
    return (res, checksums, git_source_format)


def update_crates(args):
    _stash = Stash(new_style_override_syntax=True, quiet=True)
    _stash.AddFile(args.recipe)
    _stash.Finalize()

    items = _stash.GetItemsFor(classifier=Variable.CLASSIFIER,
                               attribute=Variable.ATTR_VAR, attributeValue='CRATES_LIST')
    flags = _stash.GetItemsFor(classifier=FlagAssignment.CLASSIFIER,
                               attribute=FlagAssignment.ATTR_NAME, attributeValue='SRC_URI')
    srcrev_format = _stash.GetItemsFor(classifier=Variable.CLASSIFIER,
                                       attribute=Variable.ATTR_VAR, attributeValue='SRCREV_FORMAT')
    if not items:
        return True

    needle = items[0].RealRaw

    crates, checksums, git_source_format = get_crates(args)
    if not crates:
        return True

    crates_list = 'CRATES_LIST = "\\\n'
    for x in crates:
        crates_list += f'    {x} \\\n'
    crates_list += '"\n'

    with open(args.recipe) as i:
        raw_recipe = i.read()

    raw_recipe = raw_recipe.replace(needle, crates_list)

    # get replacement of all crates SRC_URI[...] flag settings
    for index, line in enumerate([x.RealRaw for x in sorted(
            flags, key=lambda y: y.Line) if re.search(r'.*\.(sha256sum|md5sum)', x.Flag)]):
        if index == 0:
            raw_recipe = raw_recipe.replace(line, '### !!CHECKSUM!! ###')
        else:
            raw_recipe = raw_recipe.replace(line, '')
    checksum_needle = '### !!CHECKSUM!! ###'

    # assemble new
    checksum_replacement = ''
    for name, data in checksums.items():
        checksum_replacement += f'SRC_URI[{name}.sha256sum] = "{data}"\n'

    if git_source_format:
        if any(srcrev_format):
            for item in srcrev_format:
                raw_recipe = raw_recipe.replace(
                    item.RealRaw, f'SRCREV_FORMAT = "{git_source_format}"\n')
        else:
            checksum_replacement += f'\n\nSRCREV_FORMAT = "{git_source_format}"\n'

    raw_recipe = raw_recipe.replace(checksum_needle, checksum_replacement)

    with open(args.recipe, 'w') as o:
        o.write(raw_recipe)

    return True


def main():
    args = create_parser()
    sys.exit(0 if update_crates(args) else 1)


if __name__ == '__main__':
    main()
