#! /usr/bin/env python3
import json
import glob
import os
import time
import argparse
from stat import S_ISREG, ST_CTIME, ST_MODE

def ArgumentParser():
    parser = argparse.ArgumentParser(prog="npm_package", description='Get all npm packages')
    parser.add_argument("path", help="Files to parse")
    return parser.parse_args()

if __name__ == '__main__':
    args = ArgumentParser()
    res = {}

    ## Sort by creation date to ensure the dependencies order
    items = glob.glob(os.path.join(args.path, "**", "package.json"), recursive=True)
    entries = ((os.stat(path), path) for path in items)
    entries = ((stat[ST_CTIME], path) for stat, path in entries if S_ISREG(stat[ST_MODE]))

    for _, item in sorted(entries):
        with open(item) as i:
            try:
                j = json.load(i)
                res[j["name"]] = j["version"]
            except KeyError:
                pass

    print(json.dumps(res, indent=4))