SUMMARY = "A small Python module for determining appropriate platform-specific dirs, e.g. a user data dir"
DESCRIPTION = "A small Python module for determining appropriate platform-specific dirs, e.g. a user data dir"
HOMEPAGE = "https://github.com/ActiveState/appdirs"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=31625363c45eb0c67c630a2f73e438e4"

PYPI_PACKAGE = "appdirs"

inherit pypi
inherit native
