SUMMARY = "Python HTTP library with thread-safe connection pooling, file post support, sanity friendly, and more"
DESCRIPTION = "Python HTTP library with thread-safe connection pooling, file post support, sanity friendly, and more"
HOMEPAGE = "https://github.com/urllib3/urllib3"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=ea114851ad9a8c311aac8728a681a067"

PYPI_PACKAGE = "urllib3"

inherit pypi
inherit native
