name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: apt-get install build-essential chrpath diffstat gawk gcc-multilib git-core libsdl1.2-dev python3 socat texinfo unzip wget xterm
    - name: Check out poky
      run: git clone git://git.yoctoproject.org/poky.git/ -b warrior poky
    - name: Setup poky
      run: source poky/oe-init-build-env
    - name: add meta-sca
      run: source poky/oe-init-build-env && bitbake-layers add-layes .
    - name: build
      run: source poky/oe-init-build-env && bitbake -q core-image-minimal-scatest
