name: "[nightly]"

on:
  schedule:
    - cron: "* 22 */4 * *"

jobs:
  qemu_standard:
    name: "qemux86 with standard options"
    env:
      DISTRO: scatest
      MACHINE: qemux86
      SCA_BRANCH: warrior
       
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: Update APT
        run: sudo apt-get update
      - name: Install Dependencies
        run: sudo apt-get -yq --no-install-suggests --no-install-recommends install build-essential chrpath diffstat gawk gcc-multilib git-core libsdl1.2-dev python3 socat texinfo unzip wget xterm
      - name: Check out poky
        run: git clone git://git.yoctoproject.org/poky.git/ -b $SCA_BRANCH poky
      - name: Setup poky
        run: source poky/oe-init-build-env
      - name: add meta-sca
        run: source poky/oe-init-build-env && bitbake-layers add-layer $(pwd)/..
      - name: prepare local.conf
        run: source poky/oe-init-build-env && echo 'INHERIT +="rm_work"' >> conf/local.conf
      - name: build
        run: source poky/oe-init-build-env && bitbake core-image-minimal-scatest
    
  qemu_clang:
    name: "qemux86 with meta-clang"
    env:
      DISTRO: scatest
      MACHINE: qemux86
      SCA_BRANCH: warrior
       
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: Update APT
        run: sudo apt-get update
      - name: Install Dependencies
        run: sudo apt-get -yq --no-install-suggests --no-install-recommends install build-essential chrpath diffstat gawk gcc-multilib git-core libsdl1.2-dev python3 socat texinfo unzip wget xterm
      - name: Check out poky
        run: git clone git://git.yoctoproject.org/poky.git/ -b $SCA_BRANCH poky
      - name: Check out meta-clang
        run: git clone https://github.com/kraj/meta-clang.git -b $SCA_BRANCH meta-clang
      - name: Setup poky
        run: source poky/oe-init-build-env
      - name: add meta-sca
        run: source poky/oe-init-build-env && bitbake-layers add-layer $(pwd)/..
      - name: add meta-clang
        run: source poky/oe-init-build-env && bitbake-layers add-layer $(pwd)/../meta-clang
      - name: prepare local.conf
        run: source poky/oe-init-build-env && echo 'INHERIT +="rm_work"' >> conf/local.conf
      - name: local.conf+
        run: source poky/oe-init-build-env && echo 'PREFERRED_VERSION_clang-native = "8.%"' >> >> conf/local.conf
      - name: build
        run: source poky/oe-init-build-env && bitbake core-image-minimal-scatest
      
  qemu_metaoe:
    name: "qemux86 with meta-oe"
    env:
      DISTRO: scatest
      MACHINE: qemux86
      SCA_BRANCH: warrior
       
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1 
      - name: Update APT
        run: sudo apt-get update
      - name: Install Dependencies
        run: sudo apt-get -yq --no-install-suggests --no-install-recommends install build-essential chrpath diffstat gawk gcc-multilib git-core libsdl1.2-dev python3 socat texinfo unzip wget xterm
      - name: Check out poky
        run: git clone git://git.yoctoproject.org/poky.git/ -b $SCA_BRANCH poky
      - name: Check out meta-oe
        run: git clone git://git.openembedded.org/meta-openembedded -b $SCA_BRANCH meta-oe
      - name: Setup poky
        run: source poky/oe-init-build-env
      - name: add meta-sca
        run: source poky/oe-init-build-env && bitbake-layers add-layer $(pwd)/..
      - name: add meta-oe
        run: source poky/oe-init-build-env && bitbake-layers add-layer $(pwd)/../meta-oe/meta-oe
      - name: prepare local.conf
        run: source poky/oe-init-build-env && echo 'INHERIT +="rm_work"' >> conf/local.conf
      - name: local.conf+
        run: source poky/oe-init-build-env && echo 'PREFERRED_VERSION_libzip-native = "1.%"' >> >> conf/local.conf
      - name: local.conf++
        run: source poky/oe-init-build-env && echo 'PREFERRED_VERSION_php-native = "7.%"' >> >> conf/local.conf
      - name: build
        run: source poky/oe-init-build-env && bitbake core-image-minimal-scatest
