name: "[master]-push"

on:
  push:
    branches:
      - master

jobs:
  qemux86:
    name: "build"
    env:
      DISTRO: scatest
      PYTHONIOENCODING: utf8
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      SCM_BRANCH: master
      BUILD_MAXRUNTIME: 3600

    runs-on: ubuntu-latest

    strategy:
      matrix:
        testset: [standard, globalinherit]
        include:
        - testset: standard
          BUILD_PARAMFILE: standard
          BUILD_GLOBALINHERIT: 0
        - testset: globalinherit
          BUILD_PARAMFILE: standard
          BUILD_GLOBALINHERIT: 1

    container:
      image: privkweihmann/yocto-sca-minimal:2004
      env:
        WORKSPACE: /opt/build
        TOPDIR: /opt/build
        TEMPLATECONF: /opt/build/sources/meta-sca/conf/templates/scatest-qemux86-64/
      volumes:
        - ${{ github.workspace }}:/opt/build
      options: --privileged --user=yoctouser

    steps:
      - name: setup (container)
        uses: priv-kweihmann/meta-sca-ci-utils/preparecontainer@latest
      - name: checkout (poky)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: git://git.yoctoproject.org/poky.git
          branch: ${{ env.SCM_BRANCH }}
          add-layer: "0"
      - name: checkout (meta-sca)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: https://github.com/priv-kweihmann/meta-sca.git
          branch: ${{ env.SCM_BRANCH }}
      - if: matrix.BUILD_GLOBALINHERIT == '1'
        name: setup (bitbake global inherit)
        uses: priv-kweihmann/meta-sca-ci-utils/addvar@latest
        with:
          variable: INHERIT
          operation: " += "
          value: sca
      - if: matrix.BUILD_GLOBALINHERIT != '1'
        name: setup (bitbake config)
        uses: priv-kweihmann/meta-sca-ci-utils/addvar@latest
        with:
          variable: SCA_AVAILABLE_MODULES
          value: /opt/build/sources/meta-sca/test/lang_${{ matrix.BUILD_PARAMFILE }}.txt
      - name: build (sca-modules)
        uses: priv-kweihmann/meta-sca-ci-utils/buildstep@latest
        with:
          target: core-image-minimal-scatest
          ignore-exit-codes: 124 137
