name: "[master]-push"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  qemux86:
    name: "build"
    env:
      DISTRO: scatest
      PYTHONIOENCODING: utf8
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      SCM_BRANCH: master
      BUILD_MAXRUNTIME: 600

    runs-on: ubuntu-latest

    strategy:
      matrix:
        testset: [standard]
        include:
        - testset: standard
          BUILD_PARAMFILE: standard
          BUILD_GLOBALINHERIT: 0

    container:
      image: privkweihmann/yocto-sca-minimal:latest
      env:
        WORKSPACE: /opt/build
        TOPDIR: /opt/build
        TEMPLATECONF: /opt/build/sources/meta-sca/conf/variant/scatest-qemux86-64/
      volumes:
        - ${{ github.workspace }}:/opt/build
      options: --privileged

    steps:
      - name: setup (container)
        uses: priv-kweihmann/meta-sca-ci-utils/preparecontainer@latest
      - name: setup (caches)
        run: |
          install -d -m 0777 ${WORKSPACE}/sstate-cache
      - name: configure (caches)
        uses: actions/cache@v3
        with:
          path: /opt/build/sstate-cache
          key: sca-glibc-2463638403
          restore-keys: |
            sca-glibc-
      - name: checkout (poky)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: git://git.yoctoproject.org/poky.git
          branch: ${{ env.SCM_BRANCH }}
          add-layer: "0"
      - name: checkout (meta-sca)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: https://github.com/priv-kweihmann/meta-sca.git
          branch: ${{ env.SCM_BRANCH }}
      - name: activate (caches)
        uses: priv-kweihmann/meta-sca-ci-utils/addvar@latest
        with:
          variable: SSTATE_DIR
          value: ${WORKSPACE}/sstate-cache
      - name: test (pre)
        run: |
          source sources/poky/oe-init-build-env
          find /opt/build/sstate-cache -name "*quilt-native*"
        shell: bash
      - name: build
        uses: priv-kweihmann/meta-sca-ci-utils/buildstep@latest
        with:
          target: quilt-native
      - name: test
        run: |
          source sources/poky/oe-init-build-env
          find /opt/build/sstate-cache -name "*quilt-native*"
          bitbake-diffsigs -t quilt-native patch
        shell: bash
      